confidential-containers/trustee

docs/kbs.yaml
docs/kbs_attestation_protocol.md

KBS should not only support the acquisition of keys, but also support the acquisition of multiple confidential resources. This commit revises the path of resource location and describes resources in a more unified format.
cc @sameo @Xynnn007 
Refer to: https://github.com/confidential-containers/documentation/issues/85

Document: Optimized the path of resources.

---

.github/workflows/rust.yml

In order to generate the attestation service gRPC bindings.
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>

gh: Install protoc

---

Cargo.lock
tools/client/Cargo.toml
tools/client/README.md
tools/client/src/main.rs

Updated the Client Tool to use the [KBS resource URI](https://github.com/confidential-containers/attestation-agent/blob/main/docs/KBS_URI.md) format defined by the Attention Agent.

Update Client Tool to adapt KBS resource URI.

---

Cargo.lock
Cargo.toml
src/api_server/Cargo.toml

As the underlying attestation-service fixed rev of `kbs-types`, different revs of `kbs-types` will cause the following error
```
Compiling attestation-service v0.1.0 (https://github.com/confidential-containers/attestation-service.git?rev=34d0275#34d02756)
Compiling api-server v0.1.0 (/home/kbs/src/api_server)
error[E0308]: mismatched types
--> src/api_server/src/http.rs:122:13
|
121 |         .evaluate(
|          -------- arguments to this function are incorrect
122 |             session.tee(),
|             ^^^^^^^^^^^^^ expected enum `attestation_service::Tee`, found enum `kbs_types::Tee`
|
= note: enum `kbs_types::Tee` and enum `attestation_service::Tee` have similar names, but are actually distinct types
note: enum `kbs_types::Tee` is defined in crate `kbs_types`
--> …
```

api_server: fix kbs-types version

---

Cargo.lock
Cargo.toml
docs/kbs.yaml
docs/kbs_attestation_protocol.md
src/api_server/Cargo.toml
src/api_server/src/auth.rs
src/api_server/src/http.rs
src/api_server/src/lib.rs
src/api_server/src/resource/local_fs.rs
src/api_server/src/resource/mod.rs
src/kbs/src/main.rs

This PR adds the resource registration api. Refer to the implementation of an image registry, use http POST seems a good choice.
However, as confidential resource insertion is different from retrievement, it should ensure the caller is either the owner of the KBS or the owner of the repository. For test, This pr wraps all registration-related code into a feature `unsafe`, meaning this is only for test. 
Close https://github.com/confidential-containers/kbs/pull/30

Feat resource registration

---

Cargo.lock
tools/client/Cargo.toml

At the moment the kbs test client is referencing HEAD of attestation-agent. Due to changes in the kbs-types data structures attestation service and kbs will have incompatible protocol payload. That's why we need to fix the revision, so we can iterate on the leaf packages (attestation agent/service), w/o breaking kbs.

Fix revision for attestation-agent

---

Cargo.lock
docs/kbs.yaml
docs/kbs_attestation_protocol.md
src/api_server/Cargo.toml
src/api_server/src/resource/mod.rs
tools/attest.json
tools/client/Cargo.toml

Similar to [this PR](https://github.com/confidential-containers/attestation-agent/pull/170) on attestation-agent, we need to adjust `TeePubKey` handling to reflect the updated struct on virtee/kbs-types. The fix needs to be coupled with the respective PRs:
Note: This should only be merged once the AA/AS fixes are merged. The last commit is for testing the build, using git revisions pointing to the other 2 PRs.
fixes #60

Use kbs-types v0.2.0

---

src/api_server/Cargo.toml

Fixes: #67
Hi @tnakaike This PR might help you to delete `with-in-toto` and `without-in-toto` conditions

api_server: get rid of in-toto for native-as

---

data/kbs-storage/default/security-policy/test
data/kbs-storage/default/sigstore-config/test

when `simple-signing` is enabled, by default the file `default/sigstore-config/test` will be retrieved
when `security_validate`, by default the file
`default/security-policy/test` will be retrieved
Those two default files are for quick start
Fixes: #58

docker-compose: add default rersources

---

.github/workflows/docker-build.yml
.github/workflows/rust.yml
Cargo.lock
Makefile
docker/Dockerfile
docker/Dockerfile.grpc-as
src/api_server/Cargo.toml
src/api_server/src/lib.rs
src/kbs/Cargo.toml

This PR provides the openssl option for the KBS https server because rustls does not work on s390x.
For selection of rustls and openssl, `#[cfg(not(target_arch = "s390x"))]` and `#[cfg(arget_arch = "s390x")]` are used. One curious thing is that `[target.'cfg(not(target_arch = "s390x"))'.dependencies]` does not work in src/api_server/Cargo.toml. So, we still need to comment out the dependencies manually to build kbs on s390x.
I appreciate if anyone give an advice to fix the above issue.

Add openssl support for s390x

---

.github/workflows/release.yaml
docker-compose.yml
docker/Dockerfile.grpc-as

This github action should be triggered manually to build a kbs image and publish to ghcr.io

ci: release for kbs

---

Cargo.lock
src/api_server/Cargo.toml

Hey @wainersm Could you help to review this?

chore: bump attestation-service and as-types to v0.5.0

---

data/kbs-storage/default/security-policy/test

fix the error
```
time="2023-05-03T22:58:25.218213507-04:00" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/d1a0c80eab5ac6607d6cd58458efb16f38db25601234b88dbd1bce870e0546bd/console.sock name=containerd-shim-v2 pid=3489388 sandbox=d1a0c80eab5ac6607d6cd58458efb16f38db25601234b88dbd1bce870e0546bd source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"cid d1a0c80eab5ac6607d6cd58458efb16f38db25601234b88dbd1bce870e0546bd eid d1a0c80eab5ac6607d6cd58458efb16f38db25601234b88dbd1bce870e0546bd waiting for exit signal\",\"level\":\"INFO\",\"ts\":\"2023-05-04T02:58:24.572762025Z\",\"name\":\"kata-agent\",\"source\":\"agent\",\"version\":\"0.1.0\",\"pid\":\"119\",\"subsystem\":\"rpc\"}"
INFO[2023-05-03T22:58:25.236465810-04:00] PullImage …
```

Test data: fix security policy

---

.github/dependabot.yml

For automatic tracking of dependencies and version updates.

github: Enable dependabot

---

Cargo.lock
src/api/Cargo.toml
tools/client/Cargo.toml

A fixed AS 0.6 release has been cut, context [here ](https://github.com/confidential-containers/attestation-service/issues/102)

Bump Attestation-Service dependency to v0.6.1

---

docker/Dockerfile

There were `-y` flags missing in two commands, causing the build to fail. I've also removed a surplus `apt-get update` and improved formatting of installed packages.
Adding `DEBIAN_FRONTEND=noninteractive` to env for a cleaner log without frontend warnings.

build: add missing -y flags to apt install in dockerfile

---

CODEOWNERS

Have a more formalized way of defining maintainership.
KBS is maintained by the @kbs-maintainers team.

kbs: Add a CODEOWNERS file

---

.github/workflows/e2e.yaml
.gitignore
test/Makefile

This test aims to cover a secure key release using remote-attestation. It will help us to detect unintented breakage and document a green path for the kbs protocol. Via the `./tools/client` project we retrieve evidence and request a secret from a local kbs instance, which is verifying the evidence and releasing key on successful attestation.
fixes #36
fixes #100
The idea is that we add self-hosted runners for TDX, SGX, SNP attester/verifier pairs to the test matrix. Those will most likely require self-hosted runners, that horrible yaml/json contraption in `runs-on` can be used for that.
edit: the azure cvm test will not be executed, since the repo needs to be configured to accept self-hosted runners (look [here](https://github.com/mkulke/kbs/actions/runs/5177762610/jobs/9328275847) for a …

Add e2e tests

---

Cargo.lock
Cargo.toml
docs/kbs.yaml
docs/kbs_attestation_protocol.md
src/api/Cargo.toml
src/api/src/http/attest.rs
src/api/src/http/config.rs
src/api/src/http/error.rs
src/api/src/http/mod.rs
src/api/src/http/resource.rs
src/api/src/session.rs

This PR mainly aims to add a new feature that a requester can bring the KBS-provisioned token to access the resources. The rationale behind this is the token is always short-lived, which could help decrease the risk of token leakage.
This PR also refactor the error handling of the `http` module a little to use the question mark `?` for better error handling.
Close #129

Feature: Add access resource using the KBS-provisioned Token

---

Cargo.lock
src/api/Cargo.toml
tools/client/Cargo.toml

Now points to v0.7.0 of AS and guest-components 
Part of https://github.com/confidential-containers/confidential-containers/issues/111

deps: bump dependencies for v0.7.0

---

docs/kbs.yaml

- The token to request for a resource is inside the header of the HTTP request rather than the body. And due to open api spec an Authorization header shall be ignored
- Fix illegal fields

Fix OpenAPI definition in kbs.yaml

---

.gitignore

We specify generating config/private.key and config/public.pub in docs/cluster.md. Gitignore these two files to avoid accidentally committing them.

Add keys to gitignore

---

docker-compose.yml

Right now the services are racing when running `docker-compose up`. Add depends_on clauses to the services to fix the race. This also allows running e.g. `docker-compose up kbs` which would start just KBS and its dependencies.
cc: @Xynnn007

Add docker-compose dependencies

---

docker/Dockerfile
docker/Dockerfile.amber
docker/Dockerfile.coco-as-grpc

update builder iamge from 1.67 to latest.
Arm CCA's dep `half` requires rust version >=1.70
helps https://github.com/confidential-containers/kbs/pull/76
cc @chendave @jialez0

dockerfile: update builder image

---

.github/workflows/rust.yml

This way, other matrix runs won't be canceled if one of them fails.

ci: don't fail fast on matrix runs

---

docker/Dockerfile

Improvements and fixes:
* openssl-sys fails to build without certain .pm files so the intermediate fix is to install perl.
* reduce build steps and move "COPY" later in the build to allow caches to be used more efficiently (previously, a single modification to the repo files forced 1G of apt-get to be re-installed).
* move away from deprecated apt-key.

docker: update key-broker-service Dockerfile

---

Makefile

The `.PHONY` directive for `passport-resource-kbs` spells "passport-kbs" and doesn't match the target name.

Fix the passport-resource-kbs Make target name

---

Cargo.lock
Cargo.toml
config/docker-compose/kbs-config.toml
config/kbs-config-amber.toml
config/kbs-config-grpc.toml
config/kbs-config.json
config/kbs-config.toml
config/kubernetes/base/deployment.yaml
config/kubernetes/base/kbs-config.json
config/kubernetes/base/kbs-config.toml
config/kubernetes/base/kustomization.yaml
docker-compose.yml
docs/config.md
src/api/Cargo.toml
src/api/src/attestation/amber/mod.rs
src/api/src/attestation/coco/builtin.rs
src/api/src/attestation/coco/grpc.rs
src/api/src/attestation/mod.rs
src/api/src/config.rs
src/api/src/http/mod.rs
src/api/src/lib.rs
src/api/src/policy_engine/mod.rs
src/api/src/resource/local_fs.rs
src/api/src/resource/mod.rs
src/api/src/token/mod.rs
src/kbs/Cargo.toml
src/kbs/src/main.rs
test/Makefile
test/data/e2e/kbs.toml
test/data/e2e/resource-kbs.toml

This PR refactors the KBS configuration scheme.
See commit message for details about the change set.
Fixes #78.
cc: @Xynnn007 @surajssd

Refactor config

---

test/Makefile
test/data/e2e/kbs.toml
test/data/e2e/resource-kbs.toml

- Bins are installed locally
- Reduced noisy output
- Use as much local resources as possible (AS/RVPS still uses a hardcoded /opt/coco location, issue [here](https://github.com/confidential-containers/attestation-service/issues/151))
- Reorganized the e2e test, with pid files and orderly service startup/shutdown

Fixed e2e bgcheck + passport tests

---

Cargo.lock

Since kbs references AS head, we just need to recreate a lock file

Recreate Cargo.lock file to retrieve latest AS

---

Cargo.lock
docker/Dockerfile
quickstart.md
src/api/Cargo.toml
src/api/src/resource/mod.rs
tools/client/Cargo.toml

Let's wait guest-components to be released and then change the rev insode `tools/client`.
Step 10 in https://github.com/confidential-containers/confidential-containers/issues/145

Bump KBS to v0.8.0

---

attestation-service/attestation-service/src/verifier/tdx/claims.rs

Allow kernel parameter values to contain equal signs, for example:
```
module_foo=bar=baz,wibble_setting=2
```
Fixes: #163.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

attestation: verifier: tdx: Allow equals in kernel param values

---

attestation-service/verifier/src/az_snp_vtpm/mod.rs
attestation-service/verifier/src/lib.rs
attestation-service/verifier/src/snp/mod.rs

Currently the milan vendor certs from AMD are bundled and parsed each time there is verification in process attestation. While this should never fail, we cannot `panic!` as it would impact healthy TEE implementations.
As an alternative we can fail fast on init of the verifier, indicating a problem at an earlier point. We also don't need to process the raw bytes multiple times, the vendor certs can be cached once parsed.
This impacts both SNP verifiers (`snp` + `az-snp-vtpm`)

attestation-agent: fail fast on broken AMD certs

---

attestation-service/verifier/src/csv/mod.rs

1. Remove unnecessary Base64 encoding from the Evidence structure and replace it with native structure content. This is because in the parameters of the AS top-level API, we assume that Evidence has already undergone Base64 encoding once, and the structure here serves as an internal interface parameter, so there is no need to repeat Base64 encoding.
2. Added the Serial number field in the Evidence structure, serial number is to identify the HYGON chip ID. This field improves the completeness of CSV evidence, allowing for different release logic to be set for different HYGON chips when setting AS policies. This modification comes from the needs of scene users.
3. Added the content of report data in the parsed Claims.
cc @Xynnn007 @BaoshunFang

CSV Verifier: Update Evidence format

---

.github/workflows/kbs-rust.yml
kbs/README.md
kbs/config/kbs-config-amber.toml
kbs/config/kbs-config-intel-trust-authority.toml
kbs/docker/Dockerfile.intel-trust-authority
kbs/docs/config.md
kbs/src/api/Cargo.toml
kbs/src/api/src/attestation/intel_trust_authority/mod.rs
kbs/src/api/src/attestation/mod.rs
kbs/src/api/src/config.rs
kbs/src/kbs/Cargo.toml
kbs/src/kbs/src/main.rs

Amber is officially called Intel Trust Authority and the code name is not to be used anymore.
Fixes: #87

Rename Amber to Intel Trust Authority

---

Cargo.lock
attestation-service/verifier/Cargo.toml
attestation-service/verifier/src/cca/mod.rs
attestation-service/verifier/test_data/cca-claims.json

CCA validation by the Verasion has some overlapping with the RVPS, the similar validation has been done by the Verasion already. So the validation of evidence in CoCo is not needed in theory.
The parse of the CCA token here is to align with other verifier, e.g. TDX, and to support RVPS if that is the case of future planning.
NOTE that each of the value we get from EAR is base64 encoded hex value. So, the reference value that are registered for RVPS are expected to be base64 encoded hex value as well.
[1] https://datatracker.ietf.org/doc/draft-ietf-rats-ar4si/

Cca: Get the evidence from EAR (EAT Attesation Result)

---

attestation-service/Dockerfile.as

Everytime executing cargo build, the Cargo.lock will be updated. This will bring unexpected build error when the upstream of dependency updates. `-locked` parameter will help to fix the dependency version in Cargo.lock, thus prevent unexpected build error.
Fixes #260

Fix dependency version when building container image

---

Cargo.lock
kbs/test/Makefile
kbs/tools/client/Cargo.toml

api-server is never used in client tool. Also if the dependency is included, the build process will fail because wrong feature configured.
cc @jialez0

kbs/tool: remove unless dependency

---

.github/workflows/kbs-build-and-push.yaml

Now we only build kbs-built-in-coco-as every merging to main. We also need kbs-grpc-coco-as. In this way we can test whether the current KBS cluster (kbs-grpc-coco-as, coco-as, rvps and coco-keyprovider) works well together.
cc @mythi

ci: build grpc kbs every merge to main

---

Cargo.lock
kbs/config/kbs-config-grpc.toml
kbs/src/api/Cargo.toml
kbs/src/api/src/attestation/coco/builtin.rs
kbs/src/api/src/attestation/coco/grpc.rs
kbs/src/api/src/attestation/intel_trust_authority/mod.rs
kbs/src/api/src/attestation/mod.rs
kbs/src/api/src/http/attest.rs
kbs/src/api/src/http/config.rs
kbs/src/api/src/http/resource.rs
kbs/src/api/src/lib.rs
kbs/src/api/src/session.rs
kbs/src/kbs/src/main.rs

Currently we are using a global Mutex to protect the only one attestation service client from unsafe thread sync & send. This brings performance bottle neck.
This commit brings some optimization to promote the performance and stability.
1. Abondon the global Mutex of the attestation service and change the API definition of Attest to non-mut. This would let the developers to handle the concurrency safe inside the concrete attestation-service inside. In this way, we prevent to lock the whole process logic.
2. Bring in a gRPC client pool to grpc-coco-as mode. This will help to avoid errors that caused by runing out all the temporaty ports provided by OS.
3. Replace the Mutex of session map with a concurrency-safe HashMap to avoid bottle neck.
Fixes #256

KBS/perf: promote the concurrency performance of KBS

---

kbs/src/api/src/http/attest.rs
kbs/src/api/src/http/error.rs
kbs/src/api/src/http/mod.rs
kbs/src/api/src/http/resource.rs
kbs/src/api/src/lib.rs
kbs/src/api/src/session.rs

Currently we are using a global Mutex to protect the only one attestation service client from unsafe thread sync & send. This brings performance bottle neck.
This commit will create a temporary client object to handle the current attestation request, which can break the mutex.
Fixes #256

KBS: Optimize performance and memory usage

---

attestation-service/verifier/src/az_snp_vtpm/mod.rs
attestation-service/verifier/src/cca/mod.rs
attestation-service/verifier/src/csv/mod.rs
attestation-service/verifier/src/lib.rs
attestation-service/verifier/src/sgx/mod.rs
attestation-service/verifier/src/snp/mod.rs
attestation-service/verifier/src/tdx/mod.rs

We used to compare the runtime/init data without caring about the length of each other. This commit resize the input expected data by trim or append '\0' to the equal length with the actual value from the one in evidence.
In this way we can avoid unexpected failures.
The error was firstly caught in enclave-cc's CI https://github.com/confidential-containers/enclave-cc/actions/runs/7299054486/job/20112097547?pr=312

AS/Verifier: fix the report/init data comparation

---

.github/workflows/as-build-and-push.yaml
attestation-service/attestation-service/src/lib.rs
attestation-service/rvps/Dockerfile
attestation-service/rvps/src/bin/rvps.rs

This PR fixes some bugs for RVPS
1. Avoid duplicated launch parameter flag to prevent the process from panic
2. Fix the Dockerfile LABEL and error information for RVPS.
3. Publish the RVPS image every merge to main so that we can test the KBS cluster in time.

Fix RVPS binary building & push image every merge to main

---

.github/workflows/kbs-e2e-az-snp-vtpm.yaml
.github/workflows/kbs-e2e-sample.yaml
.github/workflows/kbs-e2e.yaml
kbs/hack/ci-helper.sh

We want to be able to test PRs in a real TEE on self-hosted runners. By
default the tests are executed in the fork from which the PR is crated.
The fork does not have the self-hosted runners which provide the TEE. We
need to run them in the scope of the target repository in a safe fashion
that prevents untrusted PRs from running arbitrary code on self-hosted
runners.
fixes: #223
This change is modelled after simular workflows in kata and CAA repos.
The matrix-based kbs-e2e workflow has been turned into a reusable
workflow that is being called by specific TEE workflows. In this PR that
would be the "sample" and "az-snp-vtpm" TEE.
For a real TEE we follow the following ceremony:
1) verify whether the PR is authorized to run (a maintainer needs to set
a label on the PR).
2) checkout the main …

e2e-test: enable real TEE on self-hosted runners

---

.github/workflows/kbs-e2e-az-snp-vtpm.yaml
.github/workflows/kbs-e2e-sample.yaml
.github/workflows/kbs-e2e.yaml

Context: https://github.com/confidential-containers/kbs/actions/runs/7523718849
The attempt to find the workflow failed because there is a typo (yml => yaml). But we should also reference a workflow in the same repository locally as described here:
https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
Drive-by fix: artifact-download@v4 puts the artifacts in an `./artifact` subfolder.

e2e: reference kbs-e2e.yaml worfklows locally

---

attestation-service/verifier/Cargo.toml
attestation-service/verifier/src/az_snp_vtpm/mod.rs

A TPM quote's qualifyingData (nonce) is not padded to 64 bytes, it's of dynamic size and will be the same size as the passed-in nonce when requesting a Quote. Hence verification will fail using the padded report_data.
Also split up Quote verification into signature and nonce verification, so we can later move verification to upper layers (w/ report_data being part of the claim)

az-snp-vtpm-verifier: remove report_data padding

---

Cargo.lock
attestation-service/verifier/Cargo.toml
kbs/tools/client/Cargo.toml

1. Support more platform and launch API.
2. Support openssl 3.2.0.

kbs: Update csv-rs dep to rev b74aa8c.

---

README.md
attestation-service/README.md
kbs/README.md
kbs/quickstart.md

General improvements to KBS documentation
~~WIP for now.~~
@bpradipt @tylerfanelli lmk if there is anything you'd like me to add

Improve Documentation

---

.github/workflows/kbs-e2e-az-snp-vtpm.yaml

There is a flaw in the checkout logic of the PR, which will always default to `main`, but it should pick the head of the PRs repo.
The e2e tests were not authorized to run on pushes to main, which has been fixed, too.

ci: fetch the head of a PR in kbs TEE runs

---

.github/workflows/kbs-e2e-az-snp-vtpm.yaml

On a github runner rebases might fail because there is no git user configured.
Adopted a fix from the CAA repo:
https://github.com/confidential-containers/cloud-api-adaptor/blob/a326448163882740fbaf25ceb1b16dafa784636c/hack/ci-helper.sh#L14C1-L19C2

ci: Add default user for git rebase

---

kbs/test/Makefile

blocked-by: #309 
The self-hosted runners do not ship with openssl headers, so we need to install them explicitly.

ci: install libssl-dev for e2e on self-hosted runners

---

kbs/docs/cluster.md

This PR fixes a typo in the cluster documentation.

docs: Fix typo in cluster documentation

---

attestation-service/rvps/README.md

This PR tries to improve the RVPS document, first by putting a pre-requisite to avoid the failure when building the RVPS and by correcting a command that will fail otherwise when installing the RVPS.

docs: Improve RVPS document

---

.github/workflows/actionlint.yml
.github/workflows/kbs-e2e-az-snp-vtpm.yaml
.github/workflows/kbs-e2e.yaml

Sorry about the never-ending stream of CI-related PRs, but launching `pull_request_target` workflows w/ rebases and self-hosted runners is pretty much a shot in the dark (the PRs will run the workflows from the main branch). Actionlint will verify the workflows workflows, so at least obvious problems are caught.

ci: introduce actionlint and fix findings

---

kbs/config/kbs-config.toml

Just like in commit 5cc31e72b91eb, added the RVPS config in kbs/config/kbs-config.toml so that the example on the quickstart.md works.
Fixes #320
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

kbs/config: add RVPS config

---

.github/workflows/kbs-e2e.yaml
Cargo.lock
kbs/test/Makefile
kbs/test/data/e2e/kbs.toml
kbs/test/data/e2e/resource-kbs.toml

token-cert-chain.pem, ca-cert.pem and token-key.pem are specified in the configfiles. Without them a launch of kbs or resource-kbs will fail. Hence they are added as dependencies in the Makefile.

ci: set certs/key as makefile deps in e2e test

---

.github/workflows/kbs-e2e-az-tdx-vtpm.yaml
.github/workflows/kbs-e2e.yaml
kbs/test/Makefile

This adds a target for the az-tdx-vtpm TEE.
~TDX verifiers need an SGX quoting environment, for this we need to startup a local certificate caching service (PCCS) and point the quoting config to it.~
~The PCCS itself will need an API key to be able to query certificates from Intel's servers. If the apikey secret is set as a param to the callable workflow, it will install PCCS locally.~
We can use intel's collaterals service directly in the dcap configuration, however we need to add the local cert cache, so the endpoint is not hit by too many requests from the CI.
The workflow itself will not be executed in this PR (only after it has been merged) to test whether it works I ran the following on an Azure TDX VM Ubuntu 22.04 vm.
```bash
sudo apt-get update
sudo apt-get install make -y
git …
```

ci: add az-tdx-vtpm workflow for e2e tests

---

kbs/Makefile
kbs/quickstart.md
kbs/sample_policies/README.md
kbs/sample_policies/allow_all.rego
kbs/sample_policies/deny_all.rego
kbs/tools/client/README.md

I'm trying to catch up with latest changes of KBS project by following the [quickstart](https://github.com/confidential-containers/kbs/blob/main/kbs/quickstart.md). From within a fresh Ubuntu 22.04 VM (non TEE), I could run the  instructions for the KBS on background check mode but not before fixing some instructions. I took that opportunity to have some improvements to the doc.

kbs: improvements to quickstart and misc

---

.github/workflows/as-basic.yml
.github/workflows/as-e2e.yml
.github/workflows/kbs-docker-e2e.yaml
.github/workflows/kbs-e2e.yaml
.github/workflows/kbs-rust.yml
attestation-service/attestation-service/src/config.rs
attestation-service/verifier/src/cca/mod.rs
attestation-service/verifier/src/csv/mod.rs
attestation-service/verifier/src/sample/mod.rs
attestation-service/verifier/src/snp/mod.rs
attestation-service/verifier/src/tdx/eventlog.rs
attestation-service/verifier/src/tdx/mod.rs
attestation-service/verifier/src/tdx/quote.rs
kbs/src/api/src/policy_engine/opa/mod.rs

1. Fixes nightly lint error
2. Follow [the discussion](https://github.com/confidential-containers/confidential-containers/issues/193) from @portersrc , I fix the version of rust nightly compiler in GHA to avoid unexpected CI errors everytime new rust nightly version is released.

CI: Fix nightly lint error & fix rust nightly version

---

Cargo.lock
Cargo.toml
attestation-service/verifier/Cargo.toml
kbs/src/api/Cargo.toml
kbs/src/api/src/attestation/intel_trust_authority/mod.rs

bump: jsonwebtoken to 9

---

.github/workflows/as-basic.yml
.github/workflows/kbs-rust.yml

ubuntu-latest is not focal anymore and will eventually move to 24.04. Therefore, use a pinned ubuntu-<version> runner and match the DCAP packages repository path with it.
The same fix was done in https://github.com/confidential-containers/guest-components/pull/350

ci: fix DCAP package install

---

Cargo.lock
Cargo.toml
attestation-service/attestation-service/src/config.rs
attestation-service/attestation-service/src/lib.rs
attestation-service/attestation-service/src/rvps/builtin.rs
attestation-service/attestation-service/src/rvps/mod.rs
attestation-service/rvps/Cargo.toml
attestation-service/rvps/Dockerfile
attestation-service/rvps/README.md
attestation-service/rvps/src/bin/rvps.rs
attestation-service/rvps/src/bin/server/config.rs
attestation-service/rvps/src/bin/server/mod.rs
attestation-service/rvps/src/config.rs
attestation-service/rvps/src/lib.rs
attestation-service/rvps/src/native.rs
attestation-service/rvps/src/store/local_fs/mod.rs
attestation-service/rvps/src/store/local_json/mod.rs
attestation-service/rvps/src/store/mod.rs
docker-compose.yml
kbs/config/as-config.json
kbs/config/kbs-config.toml
kbs/config/kubernetes/base/as-config.json
kbs/config/kubernetes/base/kbs-config.toml
kbs/config/rvps.json
kbs/docs/config.md
kbs/src/api/Cargo.toml
kbs/test/data/e2e/kbs.toml

Close #179 
Close #338 
This PR adds a JSON file storage backend. To leverage this, we need to specify some parameters like the file path of the JSON. Thus also add an overall RVPS config to set different parameters of RVPS. To avoid backward compatibility problems, if no config is provided, a legacy configuration file will be used as default.

Add configuration file for RVPS and add support for JSON fs storage

---

.github/workflows/as-e2e.yml
attestation-service/README.md
attestation-service/docs/grpc-as.md
attestation-service/docs/restful-as.md
attestation-service/rvps/Dockerfile
attestation-service/rvps/README.md
attestation-service/verifier/src/lib.rs
kbs/docker/Dockerfile.coco-as-grpc
kbs/docker/Dockerfile.intel-trust-authority
kbs/docs/cluster.md

This commit is for the name-changing of kbs repo.
Related to #250

docs: fix repo name from kbs to Trustee

---

README.md
kbs/README.md

Fixup a few places where we refer to the "KBS Cluster." Now we call that Trustee.

Use the Trustee name in a few more places

---

.github/workflows/kbs-client-build-and-push.yaml
kbs/Makefile

This PR attempts to partially address https://github.com/confidential-containers/trustee/issues/333
It adds a workflow to build a statically linked kbs-client and push it to ghcr.io.
Limitations: It only covers x86-64 linux for now. It only supports the `sample_only` kbs-client.

Build and push kbs-client binary

---

.github/workflows/kbs-client-build-and-push.yaml

This is an attempt to fix the permission error seen here:
https://github.com/confidential-containers/trustee/actions/runs/8502445853/job/23286620681#step:6:13
Related issue:
Issue https://github.com/confidential-containers/trustee/issues/333
Original/merged PR (successfully created staged-images/kbs-client package and sha-based tag but failed to add latest tag):
PR https://github.com/confidential-containers/trustee/pull/349
Related [github docs](https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#about-scopes-and-permissions-for-package-registries) suggest to me that the package should have never been uploaded in the first place without this write permission, so I'm not 100% confident in this PR. An alternative might be to have a trustee admin …

Add write-packages permission for kbs-client-build-and-push workflow

---

attestation-service/attestation-service/src/bin/grpc/mod.rs
attestation-service/attestation-service/src/bin/restful-as.rs
attestation-service/attestation-service/src/config.rs
attestation-service/attestation-service/src/lib.rs
attestation-service/attestation-service/src/rvps/builtin.rs
attestation-service/attestation-service/src/rvps/grpc.rs
attestation-service/attestation-service/src/rvps/mod.rs

Replace anyhow error crate with thiserror crate
Fixes: #231

attestation-service: Refactor errors in attestation module

---

kbs/docs/initdata.md

Close https://github.com/confidential-containers/confidential-containers/issues/171
This PR aims to give a standard spec of initdata mechanism and its application in CoCo.
After agreement on the RFC, we can carry on concrete work on kata-agent side.
cc @confidential-containers/tsc @danmihai1 @arronwy @jialez0 @mkulke @huoqifeng @yuguorui @tylerfanelli 
please take a review if you get time, thanks in advance!

[RFC] Initdata specification

---

Cargo.lock
Cargo.toml
kbs/docker/Dockerfile
kbs/docker/Dockerfile.coco-as-grpc
kbs/docker/Dockerfile.intel-trust-authority
kbs/sample_policies/README.md
kbs/src/api/Cargo.toml
kbs/src/api/src/http/resource.rs
kbs/src/api/src/policy_engine/mod.rs
kbs/src/api/src/policy_engine/opa/mod.rs
kbs/test/data/policy_3.rego
kbs/test/data/policy_4.rego
kbs/test/data/policy_5.rego
kbs/test/data/policy_invalid_1.rego
kbs/test/data/policy_invalid_2.rego

1) Switch from Go-based policy engine to rust-based Regorus 
2) Switch from Anyhow to thiserror for resource policy 
3) Add several unit tests and test policies
This does not touch the AS policy. I will do that later although the plan may change based on whether/how we use EAR tokens.

kbs: switch to Regorus for resource policy

---

kbs/docker/Dockerfile

related to: #153
When using debian:stable-slim as a base image the sgx verification libraries will crash when attempting to fetch an sgx collateral during td quote validation.
Using Ubuntu 22.04 as a base image fixes the crash, and is consistent with AS which uses the same base image.
(discussion [here](https://cloud-native.slack.com/archives/C039JSH0807/p1713270650840409?thread_ts=1713264500.545019&cid=C039JSH0807))
Also removed the tdx attest lib which is not required for verification and pointed the sgx repo to the correct ubuntu version.

docker: Use Ubuntu 22.04 as kbs base image

---

kbs/config/kubernetes/README.md
kbs/config/kubernetes/deploy-kbs.sh
kbs/config/kubernetes/nodeport/kustomization.yaml
kbs/config/kubernetes/nodeport/patch.yaml

Right now the KBS service is only exposed as the
ClusterIP service type. And to be able to really
use the KBS service you need to expose it using an Ingress, but this is not always feasible. So this
commit adds a way for the KBS service to be
exposed as a NodePort service type.

k8s-config: Add support for NodePort service type

---

hack/release-helper.sh
release-guide.md

This is a bash script to help trustee maintainers perform releases. As the [release guide](https://github.com/confidential-containers/trustee/blob/main/release-guide.md) changes, this script can/should change along with it.
This work follows from discussions for trustee's release process, e.g. see [here](https://github.com/confidential-containers/trustee/issues/312#issuecomment-1933023556). It is also similar in spirit to the one in peer pods [here](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/hack/release-helper.sh).
Example usage:
```
$ ./release-helper.sh -u GH_USERNAME -k GH_TOKEN -c latest -n v0.8.2
```

Add a helper script for releasing trustee

---

attestation-service/Dockerfile.as-restful
attestation-service/README.md
attestation-service/docs/grpc-as.md
attestation-service/docs/restful-as.md
attestation-service/docs/sgx_default_qcnl.conf
kbs/README.md
kbs/tools/client/README.md

The user-oriented documents have been organized and duplicate parts have been deleted to make them more organized. These tasks will help the CoCo home page documentation.
Hope this helps @surajssd

Tidy the readme and documents

---

kbs/src/api/src/http/attest.rs
kbs/src/api/src/session.rs

When an attested session sends a new attest request, the session should not do anything else but only return the old token if it is still valid. 
Close #374

KBS: fix session status

---

kbs/config/kubernetes/README.md
kbs/config/kubernetes/custom_pccs/kustomization.yaml
kbs/config/kubernetes/custom_pccs/set_custom_pccs.yaml
kbs/config/kubernetes/custom_pccs/sgx_default_qcnl.conf

The KBS crash problem (ee1a8cebb6) was difficult to debug with the "built-in-as" image since all the logs from AS were lost.
Make the k8s sample deployment to use AS separately. This also makes it aligned with what docker-compose offers by default.

k8s: docs: DCAP kustomization + non-release images

---

attestation-service/verifier/src/tdx/quote.rs

When the qvl is linked to a process, it needs to know the proper enclave loading policy. But the default policy of qvl is SGX_QL_PERSISTENT, which means that all threads will share single QvE instance.
So we set QvE loading policy to multi-thread to enhance quote verification with multi-thread support in tdx.
Fixes: #386

AS/verifier: Enhance quote verification with multi-thread support in tdx

---

.github/workflows/as-dockerbuild.yml
attestation-service/verifier/src/tdx/quote.rs

Updates the naming in the CI build step to accurately reflect the RESTful AS image, replacing the previous gRPC name.
Fixes: #388

workflows: Rename Docker build step from gRPC to RESTful

---

kbs/tools/client/src/lib.rs

The underlying kbs code expects a string in a specific b64 encoding. The client will fail to set certain policies if standard b64 encoding is used.
Not sure what the reasoning behind the b64 encoding of a policy body is, but it is very deep into the call graph in the the policy engines' [implementation](https://github.com/confidential-containers/trustee/blob/4b0b47f382e1fca216462dd7ae0764f8da056b36/kbs/src/api/src/policy_engine/opa/mod.rs#L62), so it's reasonable to change it at the client, I think.

kbs-client: encode policies with nopad-url-b64

---

.github/workflows/kbs-e2e-az-snp-vtpm.yaml
.github/workflows/kbs-e2e-az-tdx-vtpm.yaml
.github/workflows/kbs-e2e-sample.yaml
.github/workflows/kbs-e2e.yaml
kbs/test/Makefile

The e2e tests used to remove the tee != sample restriction from the policy prior to testing. Since we want to avoid using the sample attester accidentally, we can set the expected TEE in the policy.
The TEE e2e tests would fail here, because the interface of the workflow has been changed (introduced mandatory `tee` input) and it will be executed with the workflow from the main branch.
I ran the workflow is a discrete branch to test [here ](https://github.com/confidential-containers/trustee/actions/runs/9284165792/job/25545957778)(using `tee: aztdxvtpm`)

CI: set expected tee in policy within the kbs e2e test

---

kbs/src/api/src/attestation/intel_trust_authority/mod.rs

cargo clippy errors on:
```
error: equality checks against false can be replaced by a negation
--> kbs/src/api/src/attestation/intel_trust_authority/mod.rs:119:12
|
119 |         if allow == false && token.claims.policy_ids_unmatched.is_some() {
|            ^^^^^^^^^^^^^^ help: try simplifying it as shown: `!allow
```

attestation: fix clippy error in intel_trust_authority AS

---

Cargo.lock
Cargo.toml
attestation-service/README.md
attestation-service/attestation-service/Cargo.toml
attestation-service/attestation-service/src/bin/grpc/mod.rs
attestation-service/attestation-service/src/bin/restful-as.rs
attestation-service/attestation-service/src/bin/restful/mod.rs
attestation-service/attestation-service/src/lib.rs
attestation-service/docs/parsed_claims.md
attestation-service/protos/attestation.proto
attestation-service/verifier/Cargo.toml
attestation-service/verifier/src/lib.rs
attestation-service/verifier/src/se/ibmse.rs
attestation-service/verifier/src/se/mod.rs
kbs/src/api/src/attestation/coco/builtin.rs
kbs/src/api/src/attestation/coco/grpc.rs
kbs/src/api/src/attestation/mod.rs
kbs/src/api/src/http/attest.rs
kbs/src/api/src/session.rs
kbs/tools/client/Cargo.toml

Fixes: #342 
This is kbs side code and related with PR: https://github.com/confidential-containers/guest-components/pull/492/
Depends on: 
- The verifier generate the encrypted attestation-request based on hkd, CA, signing_key, a measurement key  and a nonce, the encrypted data is protected by a symmetric attestation request protection key,  which is encrypted using the Host-key document
- Verifier sends the request to attester
- Firmware on the Attester's system decrypts the request via private host-key and calculates the evidence based on the encrpted part of the request (Measurement key + nonce)
- Attester send the evidence to verifier
- Verifier recalculates the evidence based on the Configuration UID, Additional data, user-data, guest image hashes, and nonce. (its a HMAC-SHA512 with …

Verifier: Add IBM Secure Execution driver framework

---

.github/actionlint.yaml
.github/workflows/as-build-and-push.yaml
.github/workflows/kbs-build-and-push.yaml
.github/workflows/kbs-client-build-and-push.yaml
attestation-service/Dockerfile.as-grpc
attestation-service/Dockerfile.as-restful
attestation-service/attestation-service/Cargo.toml
hack/release-helper.sh
kbs/Makefile
kbs/docker/Dockerfile
kbs/docker/Dockerfile.coco-as-grpc

This PR enables all artifacts (container images and binaries) for `s390x` alongside `x86_64`. The self-hosted runner to build them is already registered as `s390x-runner-01` to the organisation.
The change was verified with a private runner as follows:
AS: https://github.com/BbolroC/trustee/actions/runs/8982469105
KBS: https://github.com/BbolroC/trustee/actions/runs/8982469108
KBS-client: https://github.com/BbolroC/trustee/actions/runs/8982469107
The artifacts are available at:
- https://github.com/BbolroC/trustee/pkgs/container/staged-images%2Fcoco-as-grpc
- https://github.com/BbolroC/trustee/pkgs/container/staged-images%2Fcoco-as-restful
- https://github.com/BbolroC/trustee/pkgs/container/staged-images%2Fkbs
- https://github.com/BbolroC/trustee/pkgs/container/staged-images%2Fkbs-grpc-as …

Enable artifacts for s390x

---

Cargo.lock
kbs/src/api/Cargo.toml
kbs/tools/client/Cargo.toml

updating kbs-client alone is not enough but it also depends on reqwest 0.12.

chore: bump guest-components and reqwest

---

attestation-service/README.md
attestation-service/verifier/src/se/README.md

- Added the document to launch KBS with IBM SE verifier
Depends on:

ibmse: add development document for ibmse verifier

---

kbs/src/api/src/lib.rs

This introduces a compiler feature check for `as` when importing `sync::Arc`. This removes the `unused_imports` warning when building as specified in #419.
Resolves: #419

Fix KBS AS build warning

---

kbs/docker/Dockerfile

After this patch, the image size will be ~215MB
```
$ docker images | grep slim
kbs     coco-as-slim      baf4fd2a16ed   37 minutes ago   215MB
```
Close #416

kbs: shrink the size of docker image

---

kbs/docker/Dockerfile.rhel-ubi

Follow-up to #403. Add runtime dependencies, as pointed out by @mythi. Also changes the builder image from Fedora to CentOS Stream.

Add runtime dependencies to Dockerfile.rhel-ubi

---

attestation-service/verifier/src/se/README.md
attestation-service/verifier/src/se/ibmse.rs

Add #[cfg(debug_assertions)] to make sure non-release code never built in release build

ibmse: add debug_assertions for debug and release branch

---

kbs/src/api/src/attestation/mod.rs
kbs/src/api/src/http/mod.rs
kbs/src/api/src/http/resource.rs

get-resource API searches `tee-pubkey` claim from the attestation token. Instead of doing the search by ourselves, simply pass the desired path and leverage `pointer()` method to do the search. This simplifies the code when the search path needs to be made configurable.
One such case as of today is when attestation service provided tokens carry `tee-pubkey` under a different claims structure. We piggyback the existing cargo features to let each AS implementation define their own search paths compile time.

kbs: simplify tee-pubkey reading from the attestation token

---

kbs/src/api/src/attestation/intel_trust_authority/mod.rs

Closes: #151 
By adding runtime data to the appraisal request and having the reportdata
correctly hashed in the quote, ITA returns it back in the token claims
under attester_runtime_data.
For this to work, the Kata rootfs must be built with a modified
guest-components with sha512 hashing:
```    
--- a/attestation-agent/kbs_protocol/src/client/rcar_client.rs
+++ b/attestation-agent/kbs_protocol/src/client/rcar_client.rs
@@ -13,7 +13,7 @@ use log::{debug, warn};
use resource_uri::ResourceUri;
use serde::Deserialize;
use serde_json::json;
-use sha2::{Digest, Sha384};
+use sha2::{Digest, Sha512};
use crate::{
api::KbsClientCapabilities,
@@ -189,7 +189,7 @@ impl KbsClient<Box<dyn EvidenceProvider>> {
nonce: String,
) -> Result<String> {
debug!("Challenge nonce: {nonce}");
-        let mut …
```

intel-trust-authority-as: add runtime data to attestation request

---

attestation-service/verifier/src/se/README.md
attestation-service/verifier/src/se/ibmse.rs

- Make root_ca optional
- Check certs offline by default

ibmse: use optional root_ca when launch kbs

---

.github/workflows/as-build-and-push.yaml
.github/workflows/kbs-build-and-push.yaml
.github/workflows/kbs-docker-build.yml
hack/release-helper.sh
kbs/docker/Dockerfile.intel-trust-authority
release-guide.md

- Refactored directory structure for building KBS docker images
- Added publishing KBS intel trust authority AS docker image on ghcr.io

ci: added publishing intel trust authority AS docker

---

attestation-service/attestation-service/src/policy_engine/mod.rs
attestation-service/attestation-service/src/policy_engine/opa/mod.rs

opa: Refactor opa module errors

---

Cargo.lock
kbs/tools/client/Cargo.toml

This is for cutting release of v0.9.0 of trustee. To align with guest-components side.

bump: guest-components to candidate v0.9.0

---

kbs/src/api/src/attestation/intel_trust_authority/mod.rs

- Added logging error message for failed appraisal request.
- Fixed typos
Sample output:
`ERROR api_server::http::error] Attestation failed: Attestation request failed: response status=400 Bad Request, message=Invalid nonce and/or run time data provided in the request`

intel-trust-authority-as: add error message log

---

kbs/Makefile
kbs/tools/client/Cargo.toml

We can't build kbs-client on s390x host with default feature including all attesters. 
I tried to add a new variable ATTESTER in Makefile, so that we can specify separate attester when building kbs-client
* by default, `make cli` will build kbs-client with all attesters
* keep feature sample_only: `CLI_FEATURES=sample_only make cli`
* specify ATTESTER: `ATTESTER=se-attester make cli`

CLI: specify ATTESTER to build kbs-client

---

kbs/.gitignore
kbs/test/Makefile
kbs/test/config/kbs.toml
kbs/test/config/resource-kbs.toml

This test will enable https for the token-kbs. The resource-kbs will remain http.
The test folder structure has been reworked a bit, so we don't end up littering the filesystem with temporary files, all temp resources should now end up in `./work` and can be safely removed without overwriting unrelated files.

ci: test use https in kbs e2e test

---

kbs/config/kubernetes/README.md

The refactor of the repository broke this link.
We also have some issues with rustup not being available on the az runners. I wasn't sure if we should add rustup installation to the tests or do it locally. wdyt @mkulke

Fix broken SE link

---

.github/workflows/kbs-e2e.yml
kbs/test/Makefile

Split the build of the binaries out to a gh-hosted runner, only the tests need to run on TEE hw.
This fixes missing build tools on self-hosted runners and improves the caching.
~Since the CI will use the workflow files on main, the test results won't reflect the changes, a test run on a fork can be seen [here](https://github.com/mkulke/trustee/actions/runs/9792837867/job/27039594116)~
n/m that doesn't apply to the sample attester

e2e-test: fix binary build on self-hosted runners

---

kbs/config/kubernetes/custom_pccs/kustomization.yaml

We recently split the nodeport yaml into an s390x
and an x86_64 directory, but we forgot to update
the custom_pccs yaml to point to the correct one.
For now let's assume that the custom_pccs will
always run on x86_64 since it's for TDX.
We might revisit that assumption in the future.

config: fix custom pccs deployment for TDX

---

Cargo.lock
Cargo.toml
kbs/Cargo.toml
kbs/Makefile
kbs/README.md
kbs/docker/Dockerfile
kbs/docker/coco-as-grpc/Dockerfile
kbs/docker/intel-trust-authority/Dockerfile
kbs/docs/config.md
kbs/docs/resource_repository.md
kbs/src/http/resource.rs
kbs/src/resource/aliyun_kms.rs
kbs/src/resource/mod.rs
tools/kbs-client/Cargo.toml

cc @jialez0 
let me take a rebase once https://github.com/confidential-containers/guest-components/pull/621 gets merged.

KBS: Add aliyun KMS as repository storage backend

---

.github/workflows/push-as-image-to-ghcr.yml
.github/workflows/push-kbs-client-to-ghcr.yml
.github/workflows/push-kbs-image-to-ghcr.yml

The following hooks:
- ACTIONS_RUNNER_HOOK_JOB_STARTED
- ACTIONS_RUNNER_HOOK_JOB_COMPLETED
could perfectly replace the existing {pre,post}-action scripts and will make a workflow independent of the runner context. This PR wipes out all GHA steps where the actions are triggered.
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

GHA: Remove {pre,post}-action steps for self-hosted runners

---

kbs/config/kubernetes/base/deployment.yaml

Fix rate limit error with docker.io/library/busybox:latest when deploying kbs.
```
Warning  Failed     76s                 kubelet            Failed to pull image "busybox": rpc error: code = Unknown
desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to copy: httpReadSeeker: failed open:
unexpected status code https://registry-1.docker.io/v2/library/busybox/manifests/sha256:50aa4698fa6262977cff89181b2664b99d8a56dbca847bf62f2ef04854597cf8:
429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit.
You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Error log in kata: https://github.com/kata-containers/kata-containers/actions/runs/10172722668/job/28136683102?pr=9999

kbs: Fix rate limit error with busybox

---

kbs/src/http/attest.rs
kbs/src/http/error.rs
kbs/src/lib.rs
kbs/src/session.rs

kbs already supports checking the Request version but any version mismatch is not correctly returned to the client (nor checked by the current RCAR client handshake).
Add an explicit kbs ProtocolVersion error that is returned when the Request version is higher than what the KBS claims to support.

kbs: add ProtocolVersion error

---

kbs/src/attestation/coco/builtin.rs
kbs/src/attestation/coco/grpc.rs
kbs/src/attestation/mod.rs

Create a common function to generate a nonce, and add a unit test for it.

kbs: Refactor nonce handling

---

kbs/docs/initdata.md

Added IBM SE fields for initdata
Added examples for digest calculation in PeerPod
Depends on:

initdata: enhance the initdata spec for PeerPod and IBM SE

---

deps/verifier/src/se/README.md
deps/verifier/src/se/ibmse.rs

Enable release image to have SE_SKIP_CERTS_VERIFICATION also
Signed-off-by: Qi Feng Huo <huoqif@cn.ibm.com>

ibmse: SE_SKIP_CERTS_VERIFICATION for all KBS image

---

deps/verifier/src/se/ibmse.rs

Use the initdata hash value directly rather than it's hex in claims.
It's more reasonable to use the fixed length hash value `initdata.digest` rather than its HEX in claims because it's more straight forward for user to set the hash value in attestation policy.
Related PR:
https://github.com/confidential-containers/guest-components/pull/616
https://github.com/confidential-containers/cloud-api-adaptor/pull/1991

ibmse: use hash rather than hex for initdata digest in claims

---

Cargo.lock
Cargo.toml
deps/verifier/Cargo.toml

Builds trigger the following warnings that are easy to fix:
warning: /home/runner/work/trustee/trustee/deps/verifier/Cargo.toml: `default-features` is ignored for tokio, since `default-features` was not specified for `workspace.dependencies.tokio`, this could become a hard error in the future
and
warning: /home/runner/work/trustee/trustee/tools/kbs-client/Cargo.toml: `default-features` is ignored for reqwest, since `default-features` was not specified for `workspace.dependencies.reqwest`, this could become a hard error in the future

chore: fix cargo warnings on missing default-features

---

Cargo.lock
Cargo.toml
kbs/docs/kbs_attestation_protocol.md
kbs/src/attestation/coco/builtin.rs
kbs/src/attestation/coco/grpc.rs
kbs/src/attestation/intel_trust_authority/mod.rs
kbs/src/attestation/mod.rs
kbs/src/http/attest.rs
kbs/src/http/resource.rs

Ref: https://github.com/confidential-containers/guest-components/pull/628

Bump kbs-types and kbs_protocol with a KBS protocol version change

---

kbs/src/token/coco.rs
kbs/src/token/mod.rs

Moving some changes from #458 to this separate PR.
While working on this, I noticed KBS can be run without `trusted_certs_paths` and have resource access approved. Are we OK with this or would it be better to have an explicit user opt-in?

kbs: token: configuration cleanup

---

kbs/Cargo.toml
kbs/src/lib.rs
kbs/src/token/jwk.rs
kbs/src/token/mod.rs

Add a new token verifier that uses JSON Web Keys (JWK) from
the configured JWK Set sources.
JWK Sets can be provided locally using file:// URL schema
or they can be downloaded automatically via OpenID Connect configuration
https:// URLs providing a pointer via "jwks_uri".

kbs: token: add verifier with JSON Web Keys

---

kbs/Cargo.toml
kbs/config/kbs-config-intel-trust-authority.toml
kbs/src/attestation/intel_trust_authority/mod.rs
kbs/src/attestation/mod.rs
kbs/src/bin/kbs.rs
kbs/src/token/mod.rs

minor cleanup to deduplicate JWK token verification code.

ita: use AttestationTokenVerifier

---

Cargo.lock
Cargo.toml
deps/verifier/Cargo.toml

- Bump az-tdx-vtpm from 0.6.0 to 0.7.0
- Bump az-snp-vtpm from 0.6.0 to 0.7.0
- Bump base64 from 0.22.0 to 0.22.1

Bump az-tdx-vtpm & az-snp-vtpm from 0.5.3 to 0.7.0

---

Cargo.lock
kbs/Cargo.toml
kbs/src/attestation/intel_trust_authority/mod.rs

Add support for azure tdxvm API and update attestation request body accordingly to chosen tee

ita: add support for Azure attestation using dedicated API

---

kbs/config/kubernetes/ita/kustomization.yaml

While testing on an environment as close as possible to the Kata Containers CI, I've noticed that we need to build ITA based on nodeport in order to get it working as expected there.
The tests I ran earlier, in a different environment, already had this based on nodeport, but I didn't realise it while reviewing bdaa4b2185d.

ita: Build the kustomization based on nodeport

---

kbs/src/http/error.rs

For doctests, there is no keyword `no-run`.
Doctests recognizes `no_run`, but this still compiles the code, which will fail in this case.
We could fixup these examples with some hidden lines so that they compile, but since we don't really use rustdoc currently, let's just have the compiler ignore these examples.

docs: fix doctest error

---

kbs/config/kubernetes/README.md
kbs/config/kubernetes/deploy-kbs.sh

In #521 I re-worked the deploy-kbs script with overlays and didn't factor in that the key.bin needed to go to a different place for ibm-se, so it was causing:
```
trustee/kbs/config/kubernetes$ ls overlays/key.bin
ls: cannot access 'overlays/key.bin': No such file or directory
```
on an SE system.
I think the least bad way to resolve this is to move the ibm-se logic up before the key.bin check and rely on the updated `DEPLOYMENT_DIR`

kbs: Fix ibm-se deployment

---

.github/workflows/as-e2e.yml
.github/workflows/as-rust.yml
.github/workflows/kbs-docker-e2e.yml
.github/workflows/kbs-e2e.yml
.github/workflows/kbs-rust.yml
.github/workflows/push-kbs-client-to-ghcr.yml

The original way to install rust dependency will not check if rust is already installed, thus it would require `rustup` be installed on the ci machine already while self-hosted CI machine may not.
We use `actions-rust-lang/setup-rust-toolchain@v1` to install rust because `actions-rs` has not been maintained for over 1 year and archived.

Ci: Install Rust via `actions-rust-lang/setup-rust-toolchain@v1` rather than `rustup`

---

deps/verifier/src/tdx/claims.rs

The original unit tests use anyhow for error handling. The results are unstable because the debug format of the anyhow error might change due to different environments. This patch replace anyhow with thiserror without changing the test aim. This would give a more robust error type defination for comparation.
cc @jodh-intel @fitzthum

verifier/tdx: fix TdShimPlatformConfigInfo parse error comparation

---

attestation-service/docker/as-grpc/Dockerfile
attestation-service/docker/as-restful/Dockerfile
kbs/docker/Dockerfile
kbs/docker/coco-as-grpc/Dockerfile
kbs/docker/intel-trust-authority/Dockerfile
kbs/docker/rhel-ubi/Dockerfile
rvps/docker/Dockerfile

Docker prefers that statements using FROM and AS have those two words in the same case and will even warn you about it if you don't.
See https://docs.docker.com/reference/build-checks/from-as-casing/

Dockerfile: fix capitalization

---

attestation-service/Cargo.toml
attestation-service/Makefile

The Makefile is a bit strict on conditional compilation. Add some conditional verifier compilation in `Cargo.toml` and introduce a new configurable `FEATURES` variable to specify feature compilation other than default features.

attestation-service: Allow conditional compilation of some features

---

Cargo.lock
deps/verifier/Cargo.toml

With the new version of this crate I think we might not need to use the `--locked` flag when we built. Should we remove it?

Bump CSV crate

---

Cargo.lock
kbs/Cargo.toml
kbs/src/attestation/intel_trust_authority/mod.rs
kbs/src/bin/kbs.rs
kbs/src/plugins/implementations/resource/aliyun_kms.rs
kbs/src/plugins/implementations/resource/pkcs11.rs

In a few parts of our code, we'd end up logging sensitive information when the KBS is running in "debug" mode.
A simple way to avoid doing that is taking advantage of the "derivative" crate, and simply omit the sensitive fields, which is the approach taken.

kbs: Avoid logging sensitive information

---

.github/workflows/push-as-image-to-ghcr.yml
attestation-service/Cargo.toml
attestation-service/Makefile
attestation-service/docker/as-grpc/Dockerfile
attestation-service/docker/as-restful/Dockerfile
attestation-service/docs/grpc-as.md
attestation-service/docs/restful-as.md
deps/verifier/src/lib.rs
kbs/Cargo.toml

Proposed in #565 by @tylerfanelli
We soon have two needs when building an AS binary / docker image to decouple verifier dependencies.
1. Select specific verifier suites when building AS binary
2. Install specific verifier software stack due to the selected verifier suites when build docker images
This patch accomplish 1, by disabling all verifiers in CoCoAS basic code and providing a `VERIFIER` env for makefile to specify the verifier suites.
For 2, we add `make dockerfile` function which also follows `VERIFIER` env to install related verifier software stack.
By default the generation of dockerfiles will use `all-verifier`.
We add target platform detecting logic to the KBS crate cargo toml to determine the built-in AS features.
Also, the CI pipeline of CoCoAS is updated.
Close #568
The …

AS: Add support for selectable verifier suites

---

attestation-service/docker/as-restful/Dockerfile

VERIFIER is not claimed as an ARG thus not take effection in the following building steps.

AS: fix restful-as dockerfile

---

.github/workflows/as-docker-build.yml
.github/workflows/build-as-image.yml
.github/workflows/build-kbs-image.yml
.github/workflows/kbs-docker-build.yml
.github/workflows/push-as-image-to-ghcr.yml
.github/workflows/push-kbs-image-to-ghcr.yml

Issue #568 highlights the need for an image build check for s390x, similar to what we have for x86_64. 
This PR addresses the need by:
- Extracting the image build steps from the push-{kbs,as}-image-to-ghcr workflow into separate workflows
- Configuring these workflows to run on PR events or after merging a PR
Notable change:
- On merge, the workflow now pushes `ghcr.io/confidential-containers/staged-images/rhel-ubi`
The changes on PR events have been verified with:
- KBS: https://github.com/BbolroC/trustee/actions/runs/11840113329
- AS: https://github.com/BbolroC/trustee/actions/runs/11839493749
The changes on merge needs to be verified after merging this PR. I will keep an eye on how it goes and bring things up immediately when something goes wrong. Thanks.
Signed-off-by: Hyounggyu Choi …

gha: Add image build check for s390x

---

.github/workflows/as-docker-build.yml
.github/workflows/kbs-docker-build.yml

The following workflows are triggered twice during a merge:
- build-kbs-image.yml
- build-as-image.yml
For self-hosted runners, which often have a limited number of available runners, this duplicate build is unnecessary and may cause CI bottlenecks.
This PR ensures the workflow of interest is skipped when `github.event_name` is `push`, which occurs during a merge.
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

gha: Skip duplicate image build on merge

---

.github/workflows/as-docker-build.yml
.github/workflows/build-as-image.yml

The current matrix configurations are more like an manual enumeration of build options expressed in verbose matrix/include/exclude statement.
The PR changes this into a simple matrix of the build and then use include to add required auxiliary fields to each of the valid matrix combinations.
(the kbs workflow already follows the same scheme)

CI: consolidate matrix configurations

---

attestation-service/src/bin/restful/mod.rs

Before this commit, if error happens during serving the API, no explicit errors information will be printed on the terminal of AS.
With this patch, there will be an `error` log saying something like
```
[2024-11-15T09:41:59Z ERROR restful_as::restful] InternalError(
Error {
context: "attestation report evaluate",
source: "Verifier evaluate failed: TDX Verifier: AA eventlog does not pass check. AAEL value : bb3dd9d0d81bcb0674b57992e6f8e8e3614fb6ce9006e7cf65c860bdea02db53df8e05b2d8479eae4fa8c8a06d5c4a88, Quote value 3f5b43108e554a781c46c3f47e6daf3de52e353358f032dc92add9b980ffdfb5e4861b7593d3d022538043c3fb72d431",
},
)
```

AS: Add error log print

---

Cargo.lock
Cargo.toml
deps/verifier/Cargo.toml
deps/verifier/src/snp/mod.rs

Fetch the VCEK cert from the KDS if it is absent in the cert chain instead of just printing a bail statement stating that the VCEK is not found.

verifier: Fetch VCEK cert from KDS instead of bailing

---

attestation-service/Cargo.toml
attestation-service/Makefile
attestation-service/config.json
attestation-service/docs/config.md
attestation-service/docs/grpc-as.md
attestation-service/docs/restful-as.md
attestation-service/src/config.rs
attestation-service/src/lib.rs
attestation-service/src/rvps/builtin.rs
attestation-service/src/rvps/grpc.rs
attestation-service/src/rvps/mod.rs
attestation-service/src/token/mod.rs
deps/verifier/src/se/README.md
kbs/Cargo.toml
kbs/config/as-config.json
kbs/config/kbs-config.toml
kbs/config/kubernetes/base/kbs-config.toml
kbs/docs/config.md
kbs/docs/self-signed-https.md
kbs/src/config.rs
kbs/test/config/kbs.toml
kbs/test_data/configs/coco-as-builtin-1.toml
kbs/test_data/configs/coco-as-builtin-2.toml
kbs/test_data/configs/coco-as-builtin-3.toml
rvps/README.md
rvps/src/config.rs

Before this commit when we only enable `restful-bin,rvps-grpc` features, the attestation service cannot be built.
This patch fixes this issue. Also, this commit deletes the `rvps-builtin` feature as the code of rvps does not bring in any new dependencies.
Related configurations are updated to make it more robust, together with the documents.

AS: fix build with rvps features

---

deps/verifier/src/snp/mod.rs

Fixes Issue [#589](https://github.com/confidential-containers/trustee/issues/589)
Change the check condition to handle multiple attestation report versions.

verifier: Change logic to check the attestation report version

---

kbs/src/plugins/implementations/resource/backend.rs

We deprecated `.` in resource uri to avoid security issues like accessing the upper directory with `..` path. However, in some cases `.` is safe like `example.txt`. This patch allows a string not starting with `.` to appear in a resource URI.
Fixes #593
cc @bpradipt

kbs: allow resource uri to have `.` in safe ways

---

kbs/src/attestation/backend.rs
kbs/src/attestation/error.rs
kbs/src/attestation/session.rs
kbs/src/error.rs

KBS: return more context about RCAR/Attestation error

---

deps/verifier/src/sgx/mod.rs
deps/verifier/src/tdx/mod.rs

This patch adds a check logic before trying to base decoding TDX/SGX quote and AAEL/CCEL.
This would do help to raise a meaningful error
message when an evidence with empty Quote is given to verifier module.
Also, when AAEL/CCEL is existed inside the evidence but without any value, the deserialization and parse will also be skipped.

verifier: add judge logic for quote and eventlog string

---

attestation-service/src/token/simple.rs

Fix bug where wrong claims were added to the token.
Also, rename claims to flattened_claims to be slightly clearer.

token: fix simple token broker

---

kbs/src/error.rs
kbs/src/token/error.rs
kbs/src/token/mod.rs

A few miscellaneous wording changes I made while on the train to thanksgiving. None of these changes are crucial, but hopefully they improve things a little bit.

Clean up some comments and error messages

---

kbs/src/api_server.rs
kbs/src/error.rs

Some more minor cleanup. This time changing around a few variable names to hopefully be clearer.

plugins: minor cleanup of api-server code

---

Cargo.lock
Cargo.toml

Some other related packages are also updated in Cargo.lock by `cargo update -p jwt-simple`
Manually for #608

chore: Update jwt-simple dependency

---

attestation-service/src/policy_engine/opa/mod.rs
attestation-service/src/token/ear_default_policy.rego

The sample attester does not report a fake productId field, but we have used productId in our tests since before EAR.
The EAR policy erroneously expects the evidence to contain a productId, this leads to generating contra-indicated tokens for EAR.
Remove this field and update the tests.
cc @lmilleri

ear: remove productId from default policy

---

attestation-service/src/policy_engine/mod.rs
attestation-service/src/policy_engine/opa/mod.rs
attestation-service/src/token/ear_broker.rs
attestation-service/src/token/simple.rs

Minor change to avoid hard-coding claim names.
Changes the policy engine to take `Vec<String>` to better suit this kind of dynamic configuration.

token: avoid hard-coding ear claim names

---

docker-compose.yml

ad991b7 disabled image pull because that pointed to release images and often times they had conflicts with local files in the repository.
As we now have staged images published on merge, we can try pulling images without forcing local builds (or local .yml editing).
Also, Compose warns about 'version' being obsolete so drop that too, while we're at it.

cluster: use latest staged images

---

kbs/src/token/mod.rs

Added new entry in default extra tee token paths for Azure VTPM ITA

token: allow KBS to verify Azure VTPM token

---

attestation-service/src/token/ear_broker.rs

without the changes, kbs-client "set-attestation-policy" gets "not supported" errors.
the changes are taken from 'simple' token broker. Both token brokers have a policy_engine instance created.

attestation-service: implement *_policy() methods for EAR token broker

---

.github/workflows/build-as-image.yml
.github/workflows/build-kbs-image.yml
.github/workflows/push-as-image-to-ghcr.yml
.github/workflows/push-kbs-client-to-ghcr.yml
.github/workflows/push-kbs-image-to-ghcr.yml
attestation-service/docker/as-grpc/Dockerfile
attestation-service/docker/as-restful/Dockerfile
kbs/Cargo.toml
kbs/Makefile
kbs/docker/Dockerfile
kbs/docker/coco-as-grpc/Dockerfile
kbs/docker/kbs-client/Dockerfile
rvps/docker/Dockerfile

Pushing AS, RVPS, KBS and KBS Client for arm64 to the project's GHCR using cross-compilation. This is an interim step. The native compilation will be introduced when arm runner is set up for CI.
Related: https://github.com/confidential-containers/trustee/issues/631

Push AS, RVPS, KBS and KBS Client for arm64

---

.github/workflows/build-as-image.yml
.github/workflows/build-kbs-image.yml
kbs/docker/kbs-client/Dockerfile

related to https://github.com/confidential-containers/trustee/pull/639
Fix CI tests failures:
* The official rust docker image above v1.78.0 supports s390x - fix following
* https://github.com/confidential-containers/trustee/actions/runs/12459314628/job/34775998845
* The multi-arch image can not be generated using manifest lists (including provenance) - fix following
* https://github.com/confidential-containers/trustee/actions/runs/12459314629/job/34776189139
* https://github.com/confidential-containers/trustee/actions/runs/12459314639/job/34776287203
* https://github.com/confidential-containers/trustee/actions/runs/12459314629/job/34776189234
* https://github.com/confidential-containers/trustee/actions/runs/12459314639/job/34776287307
* …

Fix ci failure

---

attestation-service/src/token/ear_default_policy.rego

There is no need to set claims for every platform and compare them with min. We can just set the claims directly and rely on short-circuiting to skip any platforms that don't have TCB claims set.

Improve EAR policy

---

kbs/config/kubernetes/base/kbs-config.toml

The Kata CI does not setup the attestation token signing keys. This causes the KBS to break when we bump the repo version and pick up this new config which had the signing key specified.
In the future we can change the CI to setup the signing keys (although we are already testing this in our Makefile test), but for now let's stick with the existing behavior.

k8s: remove token signer from k8s config

---

kbs/src/token/jwk.rs

Instead of just warning and proceeding, as done right now[0], let's bail as the current behaviour leads to an unusable KBS[1].
By bailing earlier at that point, when trustee pod is being deployed by the trustee-operator, we ensure that the pod will error out and kubernetes will take care of restarting the pod till its startup properly succeeds.
[0]:
```
[INFO  kbs] Using config file /etc/kbs-config/kbs-config.json
[WARN  kbs::token::jwk] error getting JWKS: SourceAccess("error sending request for url (https://portal.trustauthority.intel.com/.well-known/openid-configuration)")
[INFO  kbs] Starting HTTP server at [0.0.0.0:8080]
[WARN  kbs::token::jwk] error getting JWKS: SourceAccess("error sending request for url (https://portal.trustauthority.intel.com/.well-known/openid-configuration)") …
```

kbs: Bail if the jwk sets cannot be downloaded

---

deps/verifier/src/se/ibmse.rs

The EAR token broker does not insert the `report_data` for SE attestation claim because there is no matching field in `SeAttestationClaims`. The absence leads to `TokenVerifierError(NoTeePubKeyClaimFound)` after successful attestation.
As an interim solution, this PR renames the existing `user_data` to `report_data`, enabling the token broker to perform its task correctly.
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

verifier: Rename user_data to report_data in SeAttestationClaims

---

deps/verifier/src/snp/mod.rs

The EAR broker expects the verifier to include `report_data` in the TCB claims as a signal that the verifier has checked the binding of the report data and the hw evidence.
Since we do check `report_data` in the SNP verifier, add the claim. Also add `init_data` claim for similar reasons.

Snp add report claim

---

Cargo.lock
Cargo.toml
attestation-service/Cargo.toml
attestation-service/src/token/simple_default_policy.rego
integration-tests/Cargo.toml
integration-tests/tests/integration.rs
kbs/Cargo.toml
kbs/Makefile
kbs/src/api_server.rs
kbs/src/bin/kbs.rs
kbs/src/lib.rs

Creates a framework for writing Trustee integration tests in Rust.
Put your tests in `integration-tests/tests/integration.rs` (or a similar file) and they will run when you do `cargo test` at the top level. 
I've added two simple integration tests. They aren't anything beyond what we already have in other tests, but they add a structure that should help us to create a lot more. Before I get too carried away, please take a look at the setup.
Note that running the KBS in the background was trickier than expected. I think I found a pretty good way to do it in the end.

Setup integration tests

---

attestation-service/src/token/ear_default_policy.rego

Something I drafted together with @jorgealmansa.
Populate the default EAR policy with an initial TDX policy configuration.

ear: add TDX sample policy checks

---

integration-tests/src/common.rs
integration-tests/src/lib.rs
integration-tests/tests/get_resource.rs
integration-tests/tests/integration.rs
kbs/docs/kbs_attestation_protocol.md

Main changes:
- Move the test logic out of the test harness so we can write more flexible tests using helpers provided by the harness.
- Separate the common testing code from the get_resource tests and move the common code into `src`.
- Add simple negative test
This is an incremental step towards more legit tests that have sophisticated policies and deal with reference values.

Reorganized integration tests and add negative tests

---

kbs/docs/config.md

Documentation of parameters `policy_ids` and `allow_unmatched_policy` updated to be more descriptive.

kbs: ITA: Documentation update.

---

Cargo.lock
attestation-service/src/token/ear_default_policy.rego
deps/verifier/Cargo.toml
deps/verifier/src/tdx/claims.rs
deps/verifier/src/tdx/quote.rs

Add parsing tdx td attributes from hex value and include them in claims report to be accessible in policies definition.

verifier: add parsing tdx td attributes and usage in policy

---

.github/workflows/push-kbs-client-to-ghcr.yml
hack/release-helper.sh
release-guide.md

This PR adds `kbs-client` to the release script and updates the release guide.
The PR also changes the naming convention of the staged packages in [ghcr](ghcr.io/confidential-containers/staged-images/kbs-client) to be more consistent with other packages.
Current: `sample_only-${{ matrix.arch }}-linux-gnu-${commit_sha}`.
Proposed: `sample_only-${commit_sha}-${{ matrix.arch }}`.
I see this could affect two places in the repos:
1) I'm ignoring the [example in the website](https://github.com/confidential-containers/confidentialcontainers.org/blob/d563250a124bcf407fa38a0c1bbd5572600ebaea/content/en/blog/2024/coco-without-confidential-hardware.md?plain=1#L297) (as it's still a valid example anyway).
2) There is a cloud [cloud-api-adaptor …

Update release scripting for kbs-client

---

rvps/src/bin/server/mod.rs
rvps/src/extractors/mod.rs

RwLock has better performance when reads are far more than writes.

RVPS | Replace Mutex to RwLock

---

.github/workflows/push-kbs-client-to-ghcr.yml

We recently bumped our runner images from 22.04 to 24.04. It turns out that 24.04 doesn't ship ORAS. We didn't notice this at the time because we only use ORAS in the post-merge workflow.
This step isn't needed for the self-hosted s390x runner, but supposedly the install-oras tool supports s390x so it shouldn't hurt.

workflows: install ORAS on runners

---

kbs/config/kbs-config.toml

`insecure_api` is a parameter of the admin config whereas `insecure_key` is part of the attestation token config. We use the wrong field in one of our config files.

config: fix insecure_key parameter

---

attestation-service/src/token/ear_default_policy.rego
deps/verifier/src/az_tdx_vtpm/mod.rs
deps/verifier/src/tdx/mod.rs
deps/verifier/src/tdx/quote.rs

Added tcb_status, advisory_ids and collateral_expiration_status to claims report which will be accessible in policies definition.

verifier: add tcb_info status, advisory_ids and collateral_expiration_status to policy

---

kbs/config/kubernetes/README.md
kbs/config/kubernetes/base/deployment.yaml
kbs/config/kubernetes/base/kustomization.yaml

Main focus of this PR is to fix #702.
While in here, updated the docs so users know how to change the default policy. Also bumped the kbs image version to use latest released (v0.11.0).
----
I wanted to bump the image version from the ita overlay (kbs/config/kubernetes/ita) but I realized kustomization is not replacing the base image correctly:
```
$ kustomize build | grep image:
image: ghcr.io/confidential-containers/key-broker-service:built-in-as-v0.11.0
image: quay.io/prometheus/busybox:latest
```
The `built-in-as-v0.11.0` tag above is not correct. I tried to fix it but failed miserably and now I have to switch to other stuffs....

KBS: Fix deployment of resources policy on k8s + misc changes

---

Cargo.lock
Cargo.toml
docker-compose.yml
kbs/Cargo.toml
kbs/Makefile
kbs/docker/coco-as-grpc/Dockerfile
kbs/docs/config.md
kbs/docs/plugins/nebula_ca.md
kbs/src/plugins/implementations/mod.rs
kbs/src/plugins/implementations/nebula_ca.rs
kbs/src/plugins/plugin_manager.rs

This PR adds the nebula_ca plugin.
Build trustee with the 'nebula-ca-plugin' cargo feature enabled and build a KBS image that has the nebula-cert binary
```bash
docker compose build --build-arg NEBULA_CA_PLUGIN=true --no-cache
```
Add the lines below to `kbs/config/docker-compose/kbs-config.toml`
```toml
[[plugins]]
name = "nebula-ca"
```
Start trustee
```bash
docker compose up
```
Ultimately, the plugin will be called from the CDH (https://github.com/confidential-containers/guest-components/pull/763). In the meantime, we can build and use the kbs-client I have in the branch https://github.com/cclaudio/trustee/tree/nebula-ca-plugin-test
```bash
$ git clone https://github.com/cclaudio/trustee.git -b nebula-ca-plugin-test
$ cd trustee/kbs && make cli ATTESTER=snp-attester
$ sudo make …
```

Add nebula_ca plugin

---

kbs/docs/kbs.yaml
kbs/docs/kbs_attestation_protocol.md
kbs/src/plugins/implementations/resource/backend.rs

The original cause of this change was a confusing asymetry in kbs-client where the client's set-resource command accepted resource paths without a repository part however a corresponding get-resource did not.  This was because on set-repository, the code being changed by this commit filled in a "default" repository value while ResourceUri::try_from(url::Url) called on get-resource bails out unless a path has all three components.
As agreed in Trustee Development call, the solution is to remove the kbs-protocol's provisiion for an optional repository part of resource path and make the repository path mandatory, similar to the rest of resource path parts.

kbs: make repository part of resource path mandatory

---

kbs/docker/kbs-client/Dockerfile

This is a following up for #725
Fix the CI error like https://github.com/confidential-containers/trustee/actions/runs/13757985713

ci: fix rust version of kbs-client release dockerfile to 1.80.0

---

.github/workflows/kbs-e2e.yml

Fixes: #708
az-vtpm-* runners are still 22.04 based which makes kbs-client to fail when built with the tss2 libraries and cached on 24.04 runners.
Move e2e-kbs build-binaries job back to 22.04 instead of bumping the az-vtpm-* runners to 24.04.

ci: build kbs-e2e binaries on Ubuntu 22.04

---

.github/workflows/kbs-rust.yml
kbs/docker/Dockerfile
kbs/quickstart.md
kbs/test/Makefile

kbs-client w/ tdx-attester does not depend on libtdx-attest anymore so drop that install dependency.

build: drop libtdx-attest

---

attestation-service/src/policy_engine/mod.rs
attestation-service/src/policy_engine/opa/mod.rs
attestation-service/src/token/ear_broker.rs

EAR TV names are kebab-case, which is not acceptable for OPA variables.
This results in TV names with `-` to be ignored.
This fix transforms kebabs into snakes to make OPA happy.

fix(as): make EAR TV names into acceptable OPA variable names

---

attestation-service/docker/as-grpc/Dockerfile
attestation-service/docker/as-restful/Dockerfile

The attestation service link is point to old link "https://github.com/confidential-containers/attestation-service".
New link should be "https://github.com/confidential-containers/trustee/tree/main/attestation-service"

Update attestation service source link in dockerfile

---

integration-tests/src/common.rs
kbs/docs/config.md
kbs/src/api_server.rs
kbs/src/config.rs

Parametrized request payload size which now can be configured by user by providing value in mb.
Fixes: #670

kbs: added request payload size config option

---

kbs/config/kubernetes/base/kustomization.yaml
kbs/config/kubernetes/ita/kustomization.yaml

Trustee/kbs v0.12.0 should use by default image built-in-as-v0.12.0 otherwise it is incompliant with coco operator 0.13.0
Fixes: #758

Update kbs image version

---

Cargo.lock
deps/verifier/src/tdx/eventlog.rs

There were some typo fixes upstream in the eventlog crate and a new release was cut. Let's bump our lockfile to pickup the changes and use the new function name.

verifiers: update eventlog crate

---

kbs/config/sgx_default_qcnl.conf

The current QCNL configuration has the collateral service commented out. This seems to cause problems for anyone who tries to use it.
Maybe there is some reason for this being set that i am not aware of, but this has been a big stumbling block for users.
@mythi

tdx: change default qcnl configuration

---

rust-toolchain.toml
rvps/docker/Dockerfile

rust-toolchain file will help to record a specific rust toolchain version to build the project.
For more details, see
https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
Close #772
cc @larrydewey

toolchain: add rust-toolchain file

---

.github/workflows/kbs-docker-e2e.yml
.github/workflows/kbs-e2e-sample.yml
.github/workflows/kbs-e2e.yml
.github/workflows/kbs-rust.yml
integration-tests/Cargo.toml
kbs/Makefile
kbs/test/Makefile

Enable kbs integration / e2e sample tests on arm64
* kbs integration test: https://github.com/confidential-containers/trustee/blob/main/.github/workflows/kbs-rust.yml
* kbs e2e sample test: https://github.com/confidential-containers/trustee/blob/main/.github/workflows/kbs-e2e-sample.yml
* kbs docker e2e test: https://github.com/confidential-containers/trustee/blob/main/.github/workflows/kbs-docker-e2e.yml
Test results on the fork:
* kbs integration test: https://github.com/seungukshin/trustee/actions/runs/14595864727
* kbs e2e sample test: https://github.com/seungukshin/trustee/actions/runs/14595864726
* kbs docker e2e test: https://github.com/seungukshin/trustee/actions/runs/14595864719

ci: enable kbs integration / e2e sample tests on arm64

---

attestation-service/src/token/ear_default_policy.rego

The SNP policy references a claim called `launch_measurement`, but the claim is actually just `measurement`.
cc @bpradipt @ryansavino

policy: fix SNP policy

---

kbs/config/kubernetes/README.md
kbs/config/kubernetes/overlays/ingress.yaml

The Azure AKS addon-http-application-routing add-on is deprecated and cannot be enabled on new clusters. Azure suggests to replace it with approuting, so this changed the README.md accordingly.
Also passing the ingress class via annotation is deprecated as shown on the warning below. Changed the ingress manifest to pass the class name in the spec section:
```
Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
```

kbs/config/kubernetes: update for deploying on AKS

---

kbs/sample_policies/README.md
kbs/sample_policies/affirming.rego
tools/kbs-client/src/main.rs

Recently I added a couple built-in policies to the KBS Client. These simplify the workflow for admins who are setting basic policies. Unfortunately, I didn't think to add the policy that is probably most important; the affirming policy, which basically makes sure that the attestation policy passed.

Add built-in affirming policy to KBS client

---

.github/workflows/build-as-image.yml
.github/workflows/build-kbs-client-image.yml
.github/workflows/build-kbs-image.yml
.github/workflows/push-kbs-client-image-to-ghcr.yml
.github/workflows/push-kbs-client-to-ghcr.yml
kbs/docker/kbs-client-image/Dockerfile

* Use native build for arm64 and remove the workaround for cross build
* the workaround PR: https://github.com/confidential-containers/trustee/pull/716
* Build and push kbs-client-image to ghcr to use it for trustee-operator's kuttl integration tests
* kuttl integration tests: https://github.com/confidential-containers/trustee-operator/blob/main/.github/workflows/kuttl-int-tests.yaml
* [KBS_IMAGE_NAME](https://github.com/confidential-containers/trustee-operator/blob/118b525474b744939f1387cc7be439e0e04e0bd2/Makefile#L178) and [CLIENT_IMAGE_NAME](https://github.com/confidential-containers/trustee-operator/blob/118b525474b744939f1387cc7be439e0e04e0bd2/Makefile#L179C1-L179C18) will be changed to `ghcr.io/confidential-containers/staged-images/kbs:latest` and …

ci: set up native build for arm64 and kbs-client-image

---

kbs/docs/self-signed-https.md

The typo is inside document and not code-related.  However, during setting up the KBS with HTTPS by following the document, it caused small issues.
This PR won't affect any executable files.

Fix a tiny typo in kbs document

---

attestation-service/src/token/ear_default_policy.rego

The SNP verifier returns all of its TCB claims as strings, we could adjust this to return numeric types for certain claims, but the RVPS currently stores all reference values as strings.
In the future we should update the RVPS to work with numeric types as well, but for now let's change the policy to use strings.
Fix https://github.com/confidential-containers/trustee/issues/801

policy: change expected SNP configuration values to Strings

---

docker-compose.yml

We expect the user to generate the admin keypair for the KBS (and keyprovider), but this really isn't necessary. This commit does maintain the existing workflow, so users can continue to setup their keys if they would like to and our existing guides are still valid.
We do have to make a few small tweaks to setup the keys from inside the KBS container. First, we have to install openssl inside the container. The staged container images don't have openssl in them yet (until after this PR), so let's hold off on updating the docs for now. I will make a second PR that tests out the staged images and updates the docs. For now, this will only work if you build the images yourself.
Next, we have to change how we mount the keys into the container. Currently, we mount the two key files individually. …

docker-compose: automatically generate admin keys

---

Cargo.lock
Cargo.toml
deps/verifier/Cargo.toml

Simply bumping the dependency to 6.2.1. There are some minor parsing bugs on 6.0.0 that get handled here and it would be good to include here to avoid complications later. No code changes required.
Should probably wait for https://github.com/confidential-containers/guest-components/pull/1012 to be merged first to also change the GC dependency in this PR.

Bumpin SEV library to 6.2.1

---

deps/verifier/src/cca/README.md

Explain how to install `evcli`.

fix(doc): Add missing step to CCA smoke test

---

attestation-service/src/lib.rs
attestation-service/src/rvps/builtin.rs
attestation-service/src/rvps/grpc.rs
attestation-service/src/rvps/mod.rs
attestation-service/src/token/ear_broker.rs
attestation-service/src/token/mod.rs
attestation-service/src/token/simple.rs
kbs/src/attestation/backend.rs
kbs/src/attestation/coco/builtin.rs
kbs/src/attestation/coco/grpc.rs
rvps/src/extractors/extractor_modules/in_toto/mod.rs
rvps/src/extractors/extractor_modules/sample/mod.rs
rvps/src/extractors/extractor_modules/swid/mod.rs
rvps/src/lib.rs
rvps/src/reference_value.rs

When we first made the RVPS, we assumed that most reference values would be hashes and we created a struct to keep track of this. It turns out that lots of reference values have other formats (integers, strings, etc) and even for value that are hashes, the RVPS only reports the value itself to the AS. As such, let's drop the HashValue struct and instead use a serde_json::Value to store the reference value.
One cool advantage of this is that reference values can take almost any format. For instance, one reference value can actually be a map of a bunch of values. As long as the AS policy knows how to use the value, everything should work out.
I also added a little hint about how we will support a pull model by supporting local and remote values. Support for remote values will be added in …

rvps: drop HashValue abstraction

---

tools/kbs-client/src/main.rs

It's not clear to know which file is not found while passing more file path parameters like tee-key-file, cert-file, attestation-token.
With this patch:
$ kbs-client --url https://trusteeserver:8080 --cert-file trustee_keys/srv_host.crt get-resource --tee-key-file trustee_keys/tee_key.pem --attestation-token /tmp/attestation_token_x --path default/test/model_encrypt_key 
Failed to read:/tmp/attestation_token_x
Error: No such file or directory (os error 2)
Without this patch:
$ kbs-client --url https://trusteeserver:8080 --cert-file trustee_keys/srv_host.crt get-resource --tee-key-file trustee_keys/tee_key.pem --attestation-token /tmp/attestation_token_x --path default/test/model_encrypt_key 
Error: No such file or directory (os error 2)

kbs-client: show file name when cannot read it

---

attestation-service/src/policy_engine/opa/mod.rs
attestation-service/src/token/ear_default_policy_cpu.rego
deps/verifier/src/sample/mod.rs
deps/verifier/src/snp/mod.rs
integration-tests/src/common.rs
integration-tests/tests/get_resource.rs
tools/kbs-client/src/lib.rs
tools/kbs-client/src/main.rs

Now that we have support for complex reference value types, let's use them.
Specifically, let's update the `kbs-client` so that we can specify integer and boolean reference values, as well as RVs that are single values (rather than a list of values).
Then, let's add some integer tcb claims to the sample verifier to show how this works.
Then, update the SNP verifier to return boolean and integer claims where it makes sense. @bpradipt @DGonzalezVillal @ryansavino might want to check this part. This will change what users need to do to provision reference values.
We may want to do something similar for other platforms. 
See commit messages for more information.

Use complex reference value types

---

Cargo.lock
attestation-service/Cargo.toml
attestation-service/src/bin/restful-as.rs

[Background]:
We are working on a Confidential AI project (https://github.com/intel/confidential-computing-zoo/tree/main/cczoo/confidential_ai),which is built based-on TDX + Open-webui. We will leverage attestation service (restful api) in trustee to do the attestation related work. Open-webui(https://github.com/open-webui/open-webui) is an open-sourced project which provides a webui for AI services.
[Description]
When Open-webui tries to access as via http, it will show below error message:
Access to XMLHttpRequest at 'http://xxxx:8080/attestation' from origin 'http://xxxx:18080' has been blocked by CORS policy: Resp                  onse to preflight request doesn't pass access control check: It does not have HTTP ok status.
[New]
Add CORS policy to permit access from open-webui …

Enable CORS support in trustee for browser scenario

---

kbs/src/api_server.rs
kbs/src/attestation/backend.rs
kbs/src/prometheus/mod.rs

Add Prometheus metrics for authentication, attestation and policy evaluation as per discussion at issue #543.
The endpoint output after some successful resource accesses will be similar to
```
$ curl http://127.0.0.1:8080/metrics
attestation_errors_total 0
attestation_requests_total 3
attestation_successes_total{tee_type="sample"} 3
auth_errors_total 0
auth_requests_total 3
auth_successes_total 3
http_request_duration_seconds_bucket{le="0.0005"} 6
http_request_duration_seconds_bucket{le="0.001"} 7
http_request_duration_seconds_bucket{le="0.005"} 13
http_request_duration_seconds_bucket{le="0.01"} 13
http_request_duration_seconds_bucket{le="0.05"} 13
http_request_duration_seconds_bucket{le="0.5"} 13
http_request_duration_seconds_bucket{le="1"} 13 …
```

KBS: more prometheus metrics

---

kbs/config/kubernetes/base/kustomization.yaml
kbs/config/kubernetes/ita/kustomization.yaml

The new images must be updated in main before the release so that they are pulled when installing the from the release branch.

kbs/config/kubernetes: update image tags for the release

---

.github/workflows/scorecard.yaml
README.md

Following from the guest-components, let's add the scorecard badge to Trustee as well.

ci: add OpenSSF scorecard workflow and badge

---

deps/eventlog/src/ccel/tcg_enum.rs

sm3 is a hash algorithm defined in ISO/IEC 10118-
3:2018. The Tcg Algorithm enum can be found in
table 3 of
https://trustedcomputinggroup.org/wp-content/uploads/TCG-Algorithm-Registry-Family-2.0-Level-00-Revision-1.35_pub.pdf

eventlog: add sm3 hash algorithm

---

kbs/src/api_server.rs
kbs/src/prometheus/mod.rs

More gradual progress on KBS's Prometheus endpoint:
- capture Prometheus metric objects' repeated/boilerplate initialisation code in macros [as suggested earlier](https://github.com/confidential-containers/trustee/pull/816#discussion_r2139146420)
-  add the active connections metric [as proposed](https://github.com/confidential-containers/trustee/issues/543#issuecomment-2916097383).

KBS: refactor in prometheus, active connections metric

---

.github/workflows/actionlint.yml
.github/workflows/as-docker-build.yml
.github/workflows/as-e2e.yml
.github/workflows/as-rust.yml
.github/workflows/build-as-image.yml
.github/workflows/build-kbs-client-image.yml
.github/workflows/build-kbs-image.yml
.github/workflows/kbs-docker-build.yml
.github/workflows/kbs-docker-e2e.yml
.github/workflows/kbs-e2e-azure-vtpm.yml
.github/workflows/kbs-e2e-sample.yml
.github/workflows/kbs-e2e.yml
.github/workflows/kbs-rust.yml
.github/workflows/link.yml
.github/workflows/push-as-image-to-ghcr.yml
.github/workflows/push-kbs-client-image-to-ghcr.yml
.github/workflows/push-kbs-client-to-ghcr.yml
.github/workflows/push-kbs-image-to-ghcr.yml

The fixes have been suggested by the zizmor static analysis tool:
https://docs.zizmor.sh/
it should be mostly uncontroversial, the only thing is maybe the transformation from input text-templating to a intermediate environment variable that actionlint/shellscripts want to quote.
```
build_option: --push --bla
```
will not work, but "option" is singular luckily. and in the end the rule is supposed to prohibit arbitrary unescaped input.
drive-by fix: the az-*-vtpm e2e test run on ephemeral runners. we need to explicitly assert group membership for unprivileged CI runs.

ci: harden gh action workflows

---

rvps/src/extractors/mod.rs

error: use of `default` to create a unit struct
Error:   --> rvps/src/extractors/mod.rs:46:45
|
46 |             Box::new(sample::SampleExtractor::default()),
|                                             ^^^^^^^^^^^ help: remove this call to `default`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs
= note: `-D clippy::default-constructed-unit-structs` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::default_constructed_unit_structs)]`

lint: fix lint error

---

.github/workflows/kbs-e2e.yml

sadly, it's not possible without subshelling and more obscure ceremony to change the runner's user group within an action and have it picked up by the succeeding steps. they are all children of the github runner process, which doesn't recognize the group assignment (it's probably also not a great idea to change the state of the runner host in a step, they runners might not all be ephemeral)
Hence we run the test with sudo for the tpm TEEs.
I confirmed the gh action code to work with a [sample run](https://github.com/mkulke/trustee/actions/runs/17493878779) and an [az-snp-vtpm run](https://github.com/mkulke/trustee/actions/runs/17493878768/job/49689944880)

e2e-test: run tpm tests with sudo

---

kbs/src/config.rs

To fix the error
error[E0063]: missing field `extractors` in initializer of `reference_value_provider_service::Config`
Error:    --> kbs/src/config.rs:313:58
|
313 |                         rvps_config: RvpsConfig::BuiltIn(RvpsCrateConfig{
|                                                          ^^^^^^^^^^^^^^^ missing `extractors`

kbs: fix config item in unit test

---

deps/verifier/src/snp/mod.rs

In line with the upcoming changes in VirTEE, I'm enabling support for Attestation Reports with Versions up to 5.

verifier: Bump Max Supported Version of Attestation Report to 5

---

Cargo.lock
Cargo.toml

Updating the guest-components used in the kbs-client to support the SEV library bump to 6.3.1 and enable Attestation Report v5.

KBS: Update kbs_protocol and kms rev

---

kbs/config/kubernetes/ita/policy.rego
kbs/src/token/mod.rs

With the move to ITA v2 appraisal API that supports composite evidence, the token claim paths got changed. The claims we used previously are now under 'tdx'.

kbs: update ITA v2 token claim paths

---

.github/workflows/kbs-e2e-azure-vtpm.yml
.github/workflows/kbs-e2e.yml
Cargo.lock
Cargo.toml
attestation-service/README.md
attestation-service/docs/grpc-as.md
attestation-service/docs/restful-as.md
attestation-service/src/bin/grpc/mod.rs
attestation-service/src/bin/restful/mod.rs
attestation-service/src/token/ear_default_policy_cpu.rego
kbs/docs/kbs_attestation_protocol.md
kbs/src/attestation/backend.rs

CompositeEvidence, RuntimeData, and InitData were all being deserialized with each KBS attestation request. Therefore, they were further integrated into the KBS protocol and added to kbs-types. Update kbs-types and use its definitions of these structs.

kbs: Update kbs-types, remove duplicate definitions
