confidential-containers/trustee

- docs/kbs_attestation_protocol.md
I just fixed a few typos while reading the document...
> fixed a few typos

- docs/kbs_attestation_protocol.md
Many folks have put significant efforts on defining that protocol, let's acknowledge that.
Signed-off-by: Samuel Ortiz <sameo@rivosinc.com>
> docs: Adds an acknowledgements section to the protocol

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/api_server/Cargo.toml
- src/api_server/src/config.rs
- src/api_server/src/http.rs
- src/api_server/src/lib.rs
- src/api_server/src/resource/local_fs.rs
- src/api_server/src/resource/mod.rs
- src/kbs/src/main.rs
- tools/client/Cargo.toml
- tools/client/README.md
- tools/client/src/main.rs
This PR uses local file as the resource repository. I'm not sure whether we need to use database. If we use database to store resources, it may mean that we need to add API endpoints to let users upload and modify resources in the database. @sameo @fitzthum
> api_server: Implement the `/resource` endpoint

- src/api_server/src/http.rs
Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>
> refactor:  make the logic more concise using macros

- .github/workflows/docker-build.yml
- Dockerfile
- README.md
> Add Dockerfile to build and deploy KBS expediently

- Cargo.lock
- Cargo.toml
- Makefile
- src/api_server/Cargo.toml
- src/api_server/src/lib.rs
- src/kbs/Cargo.toml
- src/kbs/src/main.rs
- tools/attest.sh
- tools/auth.json
- tools/auth.sh
This is the initial support for HTTPS:
* rusttls (i.e. ring, i.e. boringssl) based.
* HTTPS is enabled by default
* `--insecure-http` disables HTTPS and needs to be explicitly set
> Initial HTTPS support

- Cargo.lock
- tools/client/README.md
- tools/client/src/main.rs
And update our dependencies while at it.
> tools: client: Port to the new AA API

- docker/Dockerfile
- docker/Dockerfile.grpc-as
Signed-off-by: ChengyuZhu6 [chengyu.zhu@intel.com](mailto:chengyu.zhu@intel.com)
> docker: fixed a few typos

- .github/workflows/rust.yml
- Cargo.lock
- docker/Dockerfile
- proto/attestation.proto
- src/api/Cargo.toml
- src/api/src/attestation/coco/grpc.rs
- tools/client/Cargo.toml
This PR is a parent of the PRs to corresponding AA and AS PRs
> Include az-snp-vtpm TEE

- docs/config.md
- src/api/src/config.rs
* Improve the `Config` structure documentation
* Add a `doc/config.md` markdown file
> KBS Config documentation

- README.md
Make it point to the documentation for this file.
> README: Fix configuration file link

- .github/workflows/rust.yml
- Makefile
- README.md
- docker/Dockerfile.amber
- docs/config.md
- src/api/Cargo.toml
- src/api/src/attestation/amber/mod.rs
- src/api/src/attestation/mod.rs
- src/api/src/config.rs
- src/kbs/Cargo.toml
Project Amber is Intel’s groundbreaking Software as a Service (SaaS) implementation of an independent trust authority that provides attestation of workloads in public and/or private, multi-cloud environments.
This pull request enable kbs support amber as an attestation service for coco.
> Amber integration

- .github/workflows/release.yaml
- docker/Dockerfile
> Image built in as

- Cargo.lock
- tools/client/Cargo.toml
> bump: attestation-agent to v0.6.0

- Cargo.lock
- docs/kbs_attestation_protocol.md
- src/api/Cargo.toml
- src/api/src/attestation/mod.rs
- src/api/src/session.rs
- tools/client/Cargo.toml
> Update JWK public key format in protocol

- config/kubernetes/base/kustomization.yaml
> k8s config: Update image tag to v0.7.0

- Cargo.lock
- test/Makefile
- tools/client/Cargo.toml
- tools/client/src/lib.rs
- tools/client/src/main.rs
1. Added optional parameters for importing custom TEE public key.
2. Added optional parameters for provide custom KBS Root certificate.
3. Provided SDK format for Client Tool.
These enhancements will make the Client tool easier to use
> Update Client tool to support custom TEE pubkey and KBS certificate

- Cargo.lock
- src/api/Cargo.toml
- src/api/src/http/resource.rs
- src/api/src/resource/mod.rs
Add legality checking of resource path to avoid reading files in parent directory.
cc @Xynnn007
> Fix security issue: avoid directory interleaving vulnerabilities

- attestation-service/bin/grpc-as/src/server.rs
- attestation-service/protos/attestation.proto
Fix attestation in the case of Azure SNP vTPM
> Fix Azure SNP vTPM attestation (grpc)

- attestation-service/attestation-service/src/verifier/snp/mod.rs
Similar to #230 the verify function here is actually not checking the result of the verification.
There is a fail-test for the vcek signature verification, but it fails at parsing the DER cert. We should get rid of anyhow here and use proper error types (#231) which we can then assert in such tests.
- Fixed the verification logic
- Added test-case for toggled ark-ask
- Fixed fail-test to produce a legit VCEK
- ~failed parsing of bundled milan certs hould not produce runtime errors, but panic~
cc @fitzthum @larrydewey
> attestation-service: fix checks for VCEK signature

- Cargo.lock
- attestation-service/verifier/Cargo.toml
- attestation-service/verifier/src/az_snp_vtpm/mod.rs
Updated the crate for az-snp-vtpm TEE. Since the API evolved the verification code was adjusted slightly and the test coverage has been increased.
> attestation-service: bump az-snp-vtpm verifier

- .github/workflows/kbs-build-and-push.yaml
> kbs: Fix docker registry name in image build workflow

- attestation-service/verifier/src/tdx/claims.rs
Rework `TdShimPlatformConfigInfo` to use types for its fields to
simplify the logic in it's `try_from()` function.
Added a unit test to check the expected behaviour.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
> attestation: verifier: tdx: Rework TdShimPlatformConfigInfo try_from

- kbs/config/kubernetes/base/kbs-config.toml
RVPS config was missing so KBS would error out.
> k8s: Add RVPS config to kbs-config

- kbs/README.md
- kbs/docs/self-signed-https.md
Fixes #47
cc @sameo @fitzthum @jialez0
> KBS: add a guide for HTTPS kbs usage

- kbs/config/kubernetes/base/deployment.yaml
- kbs/config/kubernetes/base/kustomization.yaml
- kbs/config/kubernetes/base/policy.rego
Add support for configurable policy using config maps
Fixes: #391
> kbs: Add support for configurable policy

- .github/workflows/kbs-docker-build.yml
- kbs/docker/Dockerfile.rhel-ubi
Adding a Dockerfile to generate a new image, hopefully good enough for tests and experiments.
Resolves: https://issues.redhat.com/browse/KATA-3029
> Add Dockerfile for Red Hat UBI

- attestation-service/verifier/src/sgx/mod.rs
- attestation-service/verifier/src/snp/mod.rs
This PR includes work
1. Fix a bug that the retrieved collateral was not used by DCAP verification
2. Optimize the performance of SGX quote by set DCAP policy
3. some lint fixes
cc @arronwy
> AS | Fix SGX verifier & Optimization

- attestation-service/verifier/src/se/ibmse.rs
- Change ec to RSA 4096+padding
- Add algorithm to skip certs checking for developing env
- Use real CA file name for default CA
> ibmsse: change ec to rsa key

- kbs/config/kubernetes/base/kustomization.yaml
Update kustomization.yaml for next release.
> Release: Update KBS for v0.9.0

- deps/verifier/src/se/README.md
Update readme for initdata and se.user_data field in attestation policy
> ibmse: update readme to reflect initdata change

- kbs/docs/self-signed-https.md
- Fix the miscs in self-signed-https.md
When I trying the https kbs, I found some misc problems and use this PR to fix them.
> kbs: msic fix in self-signed-https.md

- Cargo.lock
- Cargo.toml
> chore: update guest-components to v0.10.0

- deps/verifier/src/az_snp_vtpm/mod.rs
- deps/verifier/src/az_tdx_vtpm/mod.rs
This is in preperation for the upcoming init_data feature.
On the attester equivalent we have settled for sha256#PCR8 to measure init_data into. This register is usually occupied by GRUB, since we use UKI images for peerpods this is vacant.
If this turns out to be too restrictive, we can add a verifier specific configuration option later.
Note: We cannot merely compare the hash values, since PCR registers are extend-only. PCR8 will be filled with 0s initially and extended with the init_data digest. For a given init_data the PCR will contain:
```bash
sha256sum -b <(cat \
<(dd if=/dev/zero of=/dev/stdout bs=32 count=1) \
<(xxd -r -ps < /run/peerpod/initdata.digest) \
)
1+0 records in
1+0 records out
32 bytes copied, 4.7e-05 s, 681 kB/s …
```
> verifier: verify init_data in az-*-vtpm verifiers

- attestation-service/src/lib.rs
Hey, it would be nice to be able to debug these types and make serialization easier. I hope you would consider merging this.
> Derive Debug for Data and Enums

- tools/kbs-client/README.md
Reflect recent project restructuring.
> Update kbs-tools README.md

- kbs/docs/self-signed-https.md
- kbs/src/plugins/implementations/resource/local_fs.rs
There are two commits, please see the concrete commit message of both.
> KBS: Fix config default value and docs

- kbs/config/kbs-config-grpc.toml
- kbs/config/kbs-config-intel-trust-authority.toml
- kbs/config/kbs-config.toml
Test locally. Fixes #570
cc @litian1992
> KBS: Update configuration file format

- attestation-service/docs/config.md
- kbs/config/kubernetes/base/kbs-config.toml
- kbs/docs/config.md
- kbs/src/config.rs
- kbs/test_data/configs/coco-as-builtin-1.toml
- kbs/test_data/configs/coco-as-builtin-2.toml
- kbs/test_data/configs/coco-as-builtin-3.toml
- kbs/test_data/configs/coco-as-grpc-2.toml
- kbs/test_data/configs/coco-as-grpc-3.toml
- kbs/test_data/configs/intel-ta-1.toml
- kbs/test_data/configs/intel-ta-2.toml
- kbs/test_data/configs/intel-ta-3.toml
> KBS/AS | Fix configuration items and update the docs

- Cargo.lock
- Cargo.toml
> chore: update protobuf suites

- rvps/Makefile
without the fix, make install fails.
> rvps: fix binary target path

- Cargo.lock
- deps/verifier/Cargo.toml
- deps/verifier/src/snp/mod.rs
The two dependencies have version dependencies so we update them together.
Close #644
> chore: update to x509-parser 0.16.0 and asn1-rs 0.6.2

- hack/release-helper.sh
We've discussed some more significant changes in the past and maybe we should do those, but for now here's a tiny fix to make the script work.
> release: fixup release helper

- deps/verifier/src/az_tdx_vtpm/mod.rs
- deps/verifier/src/intel_dcap/mod.rs
- deps/verifier/src/lib.rs
- deps/verifier/src/sgx/mod.rs
- deps/verifier/src/tdx/mod.rs
- deps/verifier/src/tdx/quote.rs
Separated duplicated ecdsa quote verification code used for dcap quote data.
> verifier: combined duplicated dcap implementation

- .dockerignore
- .github/workflows/build-as-image.yml
- .github/workflows/build-kbs-image.yml
- kbs/docker/Dockerfile
Please see the concrete commit message
Close #715
> CI | Fix segment error aarch64

- kbs/README.md
- kbs/docker/Dockerfile
> kbs/dockerfile: replace kbs by trustee

- kbs/src/attestation/intel_trust_authority/mod.rs
Included raw base64 encoded CC event logs from tee evidence in ITA attestation request
> ita: added processing event logs in SGX & TDX context

- tools/kbs-client/src/main.rs
Let's ship a couple of basic policies (allow-all, deny-all, and the default) in the KBS Client itself. This way users can easily set these policies without having to create a file.
In the future we could consider moving this functionality into the KBS itself, but for now let's avoid changing the API.
> kbs-client: add built-in policies

- kbs/config/sgx_default_qcnl.conf
😬 
btw it's interesting that we have a bunch of comments in this JSON file. I'm not sure that's legal, but it doesn't seem to be a problem.
cc @mythi
> tdx: fixup qcnl config

- attestation-service/src/token/ear_default_policy.rego
Add Azure vTPM details to ear default policy
> attestation-policy: Add Azure vTPM details

- deps/eventlog/src/ccel/ipl.rs
Added removing \0 from event output
> deps/eventlog: improve EV_IPL data parser

- .github/workflows/actionlint.yml
- .github/workflows/as-docker-build.yml
- .github/workflows/as-e2e.yml
- .github/workflows/as-rust.yml
- .github/workflows/build-as-image.yml
- .github/workflows/build-kbs-client-image.yml
- .github/workflows/build-kbs-image.yml
- .github/workflows/kbs-docker-build.yml
- .github/workflows/kbs-docker-e2e.yml
- .github/workflows/kbs-e2e-azure-vtpm.yml
- .github/workflows/kbs-e2e-sample.yml
- .github/workflows/kbs-e2e.yml
- .github/workflows/kbs-rust.yml
- .github/workflows/link.yml
- .github/workflows/push-as-image-to-ghcr.yml
- .github/workflows/push-kbs-client-image-to-ghcr.yml
- .github/workflows/push-kbs-client-to-ghcr.yml
- .github/workflows/push-kbs-image-to-ghcr.yml
Appease the scorecard.
Let's see if these are the right permissions.
> workflows: fixup token permissions

- .github/workflows/kbs-e2e-azure-vtpm.yml
This was missed apparently missed earlier.
> ci: Propagate content:read from azure e2e workflow

- Cargo.lock
- deps/verifier/Cargo.toml
Test https://github.com/virtee/sev/pull/329
> Bump SEV Crate to fix ARM build issue
